-- ============================================================================
-- TDF DATA PLATFORM - INFRASTRUCTURE TABLES
-- ============================================================================
-- Infrastructure assets: Sites, Towers, Rooftops, Indoor, Data Centers,
-- Equipment, Antennas, Broadcast Transmitters, Fibre Network
-- Scale: 8,785 Active Sites, 7,877 Towers, 21,244 Points of Service
-- ============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE TDF_WH;
USE DATABASE TDF_DATA_PLATFORM;
USE SCHEMA INFRASTRUCTURE;

-- ============================================================================
-- SITES (Master table for all TDF sites - 8,785 active)
-- ============================================================================

CREATE OR REPLACE TABLE SITES (
    SITE_ID VARCHAR(20) PRIMARY KEY,
    SITE_CODE VARCHAR(30) NOT NULL UNIQUE,
    SITE_NAME VARCHAR(200) NOT NULL,
    SITE_TYPE VARCHAR(20) NOT NULL COMMENT 'TOWER, ROOFTOP, INDOOR, DATACENTER, BROADCAST',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, INACTIVE, PLANNED, DECOMMISSIONED',
    
    -- Location
    DEPARTMENT_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.DEPARTMENTS(DEPARTMENT_ID),
    COMMUNE_ID VARCHAR(10),
    ADDRESS VARCHAR(500),
    POSTAL_CODE VARCHAR(10),
    CITY VARCHAR(100),
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    ALTITUDE_M FLOAT,
    
    -- Ownership
    LAND_OWNERSHIP VARCHAR(20) COMMENT 'OWNED, LEASED, THIRD_PARTY',
    LEASE_START_DATE DATE,
    LEASE_END_DATE DATE,
    LEASE_ANNUAL_COST_EUR FLOAT,
    LANDLORD_NAME VARCHAR(200),
    
    -- Technical
    COMMISSIONING_DATE DATE,
    DECOMMISSIONING_DATE DATE,
    MAX_TENANTS INTEGER DEFAULT 4,
    CURRENT_TENANTS INTEGER DEFAULT 0,
    COLOCATION_RATE FLOAT GENERATED ALWAYS AS (CURRENT_TENANTS / NULLIF(MAX_TENANTS, 0)) VIRTUAL,
    POWER_CAPACITY_KW FLOAT,
    BACKUP_POWER_HOURS FLOAT,
    
    -- Financial
    ANNUAL_REVENUE_EUR FLOAT,
    ANNUAL_OPEX_EUR FLOAT,
    ASSET_VALUE_EUR FLOAT,
    
    -- Risk & Quality
    RISK_SCORE INTEGER COMMENT '0-100, higher is riskier',
    LAST_INSPECTION_DATE DATE,
    NEXT_INSPECTION_DATE DATE,
    DIGITAL_TWIN_STATUS VARCHAR(20) COMMENT 'SYNCED, PENDING, DISCREPANCY',
    
    -- Audit
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'TDF_ASSET_MGT',
    SOURCE_RECORD_ID VARCHAR(50),
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- TOWERS (Steel tower structures - 7,877)
-- ============================================================================

CREATE OR REPLACE TABLE TOWERS (
    TOWER_ID VARCHAR(20) PRIMARY KEY,
    SITE_ID VARCHAR(20) NOT NULL REFERENCES SITES(SITE_ID),
    TOWER_CODE VARCHAR(30) NOT NULL UNIQUE,
    TOWER_NAME VARCHAR(200),
    
    -- Physical Characteristics
    TOWER_TYPE VARCHAR(30) COMMENT 'LATTICE, MONOPOLE, GUYED, CAMOUFLAGE',
    HEIGHT_M FLOAT NOT NULL,
    BASE_WIDTH_M FLOAT,
    WEIGHT_KG FLOAT,
    WIND_LOAD_CAPACITY_KN FLOAT,
    MAX_ANTENNA_LOAD_KG FLOAT,
    
    -- Construction
    MANUFACTURER VARCHAR(100),
    CONSTRUCTION_DATE DATE,
    INSTALLATION_DATE DATE,
    LAST_STRUCTURAL_INSPECTION DATE,
    STRUCTURAL_CONDITION VARCHAR(20) COMMENT 'EXCELLENT, GOOD, FAIR, POOR, CRITICAL',
    
    -- Capacity
    AVAILABLE_POSITIONS INTEGER,
    OCCUPIED_POSITIONS INTEGER,
    AVAILABLE_HEIGHT_M FLOAT,
    
    -- Lifecycle
    EXPECTED_END_OF_LIFE DATE,
    LIFECYCLE_STATUS VARCHAR(20) COMMENT 'NEW, OPERATIONAL, AGING, END_OF_LIFE',
    REPLACEMENT_PLANNED BOOLEAN DEFAULT FALSE,
    REPLACEMENT_YEAR INTEGER,
    
    -- Financial
    ORIGINAL_COST_EUR FLOAT,
    CURRENT_BOOK_VALUE_EUR FLOAT,
    REPLACEMENT_COST_EUR FLOAT,
    
    -- Audit
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'TDF_ASSET_MGT',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- ROOFTOPS (Building rooftop installations - 8,174 PoS locations)
-- ============================================================================

CREATE OR REPLACE TABLE ROOFTOPS (
    ROOFTOP_ID VARCHAR(20) PRIMARY KEY,
    SITE_ID VARCHAR(20) NOT NULL REFERENCES SITES(SITE_ID),
    ROOFTOP_CODE VARCHAR(30) NOT NULL UNIQUE,
    
    -- Building Info
    BUILDING_NAME VARCHAR(200),
    BUILDING_TYPE VARCHAR(50) COMMENT 'RESIDENTIAL, COMMERCIAL, INDUSTRIAL, PUBLIC',
    BUILDING_HEIGHT_M FLOAT,
    ROOF_TYPE VARCHAR(30) COMMENT 'FLAT, PITCHED, TERRACE',
    ROOF_AREA_M2 FLOAT,
    
    -- Installation
    INSTALLATION_DATE DATE,
    INSTALLATION_TYPE VARCHAR(30) COMMENT 'MAST, FRAME, WALL_MOUNT',
    MAST_HEIGHT_M FLOAT,
    MAX_EQUIPMENT_WEIGHT_KG FLOAT,
    
    -- Access
    ACCESS_TYPE VARCHAR(30) COMMENT '24_7, BUSINESS_HOURS, APPOINTMENT',
    ACCESS_RESTRICTIONS VARCHAR(500),
    KEY_CODE VARCHAR(50),
    
    -- Landlord
    LANDLORD_TYPE VARCHAR(30) COMMENT 'PRIVATE, CONDO, SOCIAL_HOUSING, PUBLIC',
    CONTRACT_TYPE VARCHAR(30),
    MONTHLY_RENT_EUR FLOAT,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- INDOOR_SITES (Indoor coverage installations - 908)
-- ============================================================================

CREATE OR REPLACE TABLE INDOOR_SITES (
    INDOOR_SITE_ID VARCHAR(20) PRIMARY KEY,
    SITE_ID VARCHAR(20) NOT NULL REFERENCES SITES(SITE_ID),
    INDOOR_CODE VARCHAR(30) NOT NULL UNIQUE,
    
    -- Venue Info
    VENUE_NAME VARCHAR(200),
    VENUE_TYPE VARCHAR(50) COMMENT 'SHOPPING_CENTER, AIRPORT, STADIUM, HOSPITAL, METRO',
    VENUE_AREA_M2 FLOAT,
    FLOORS_COVERED INTEGER,
    
    -- Technical
    DAS_TYPE VARCHAR(30) COMMENT 'ACTIVE_DAS, PASSIVE_DAS, SMALL_CELL',
    ANTENNA_COUNT INTEGER,
    COVERAGE_AREA_M2 FLOAT,
    
    -- Contract
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    ANNUAL_FEE_EUR FLOAT,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- DATA_CENTERS (Edge and Regional Data Centers - 102 Edge + 4 Regional)
-- ============================================================================

CREATE OR REPLACE TABLE DATA_CENTERS (
    DC_ID VARCHAR(20) PRIMARY KEY,
    SITE_ID VARCHAR(20) NOT NULL REFERENCES SITES(SITE_ID),
    DC_CODE VARCHAR(30) NOT NULL UNIQUE,
    DC_NAME VARCHAR(200),
    
    -- Type
    DC_TYPE VARCHAR(30) NOT NULL COMMENT 'EDGE, REGIONAL, NOC',
    DC_TIER VARCHAR(10) COMMENT 'TIER1, TIER2, TIER3, TIER4',
    
    -- Capacity
    TOTAL_RACK_CAPACITY INTEGER,
    USED_RACKS INTEGER,
    TOTAL_POWER_KW FLOAT,
    AVAILABLE_POWER_KW FLOAT,
    PUE_RATIO FLOAT COMMENT 'Power Usage Effectiveness',
    
    -- Connectivity
    FIBRE_CONNECTIONS INTEGER,
    NETWORK_CAPACITY_GBPS FLOAT,
    
    -- Location (for regional DCs)
    CITY VARCHAR(100) COMMENT 'Bordeaux, Lille, Marseille, Rennes for regional',
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- EQUIPMENT (All equipment across sites - ~80,000)
-- ============================================================================

CREATE OR REPLACE TABLE EQUIPMENT (
    EQUIPMENT_ID VARCHAR(20) PRIMARY KEY,
    EQUIPMENT_CODE VARCHAR(30) NOT NULL UNIQUE,
    SITE_ID VARCHAR(20) NOT NULL REFERENCES SITES(SITE_ID),
    TOWER_ID VARCHAR(20) REFERENCES TOWERS(TOWER_ID),
    
    -- Classification
    EQUIPMENT_TYPE_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.EQUIPMENT_TYPES(EQUIPMENT_TYPE_ID),
    EQUIPMENT_CATEGORY VARCHAR(50) NOT NULL COMMENT 'ANTENNA, TRANSMITTER, POWER, NETWORK, HVAC, SECURITY',
    
    -- Identification
    MANUFACTURER VARCHAR(100),
    MODEL VARCHAR(100),
    SERIAL_NUMBER VARCHAR(100),
    
    -- Installation
    INSTALLATION_DATE DATE NOT NULL,
    INSTALLED_BY VARCHAR(100),
    INSTALLATION_COST_EUR FLOAT,
    
    -- Lifecycle
    WARRANTY_END_DATE DATE,
    EXPECTED_END_OF_LIFE DATE,
    LIFECYCLE_STATUS VARCHAR(20) NOT NULL COMMENT 'NEW, OPERATIONAL, AGING, END_OF_LIFE, DECOMMISSIONED',
    AGE_YEARS FLOAT GENERATED ALWAYS AS (DATEDIFF(YEAR, INSTALLATION_DATE, CURRENT_DATE())) VIRTUAL,
    
    -- Condition
    CONDITION_SCORE INTEGER COMMENT '1-100, higher is better',
    LAST_MAINTENANCE_DATE DATE,
    NEXT_MAINTENANCE_DATE DATE,
    FAILURE_RISK_SCORE INTEGER COMMENT '0-100, higher is riskier',
    
    -- Financial
    ORIGINAL_COST_EUR FLOAT,
    CURRENT_BOOK_VALUE_EUR FLOAT,
    REPLACEMENT_COST_EUR FLOAT,
    
    -- Technical
    POWER_CONSUMPTION_W FLOAT,
    IS_CRITICAL BOOLEAN DEFAULT FALSE,
    
    -- Ownership
    OWNER VARCHAR(20) COMMENT 'TDF, OPERATOR',
    OPERATOR_ID VARCHAR(10),
    
    -- Audit
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'TDF_ASSET_MGT',
    SOURCE_RECORD_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- ANTENNAS (Antenna installations - ~25,000)
-- ============================================================================

CREATE OR REPLACE TABLE ANTENNAS (
    ANTENNA_ID VARCHAR(20) PRIMARY KEY,
    EQUIPMENT_ID VARCHAR(20) NOT NULL REFERENCES EQUIPMENT(EQUIPMENT_ID),
    SITE_ID VARCHAR(20) NOT NULL REFERENCES SITES(SITE_ID),
    TOWER_ID VARCHAR(20) REFERENCES TOWERS(TOWER_ID),
    
    -- Technical
    ANTENNA_TYPE VARCHAR(30) COMMENT 'PANEL, OMNI, PARABOLIC, YAGI',
    TECHNOLOGY VARCHAR(20) COMMENT '2G, 3G, 4G, 5G, DTT, RADIO, DAB',
    FREQUENCY_BAND VARCHAR(30),
    GAIN_DBI FLOAT,
    
    -- Position
    HEIGHT_M FLOAT,
    AZIMUTH_DEG FLOAT,
    TILT_DEG FLOAT,
    POLARIZATION VARCHAR(20),
    
    -- Operator
    OPERATOR_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.OPERATORS(OPERATOR_ID),
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- BROADCAST_TRANSMITTERS (TV/Radio transmitters - ~3,500)
-- ============================================================================

CREATE OR REPLACE TABLE BROADCAST_TRANSMITTERS (
    TRANSMITTER_ID VARCHAR(20) PRIMARY KEY,
    EQUIPMENT_ID VARCHAR(20) NOT NULL REFERENCES EQUIPMENT(EQUIPMENT_ID),
    SITE_ID VARCHAR(20) NOT NULL REFERENCES SITES(SITE_ID),
    
    -- Type
    BROADCAST_TYPE VARCHAR(20) NOT NULL COMMENT 'DTT, FM_RADIO, DAB_PLUS, AM_RADIO',
    SERVICE_NAME VARCHAR(100) COMMENT 'Channel/Station name',
    
    -- Technical
    FREQUENCY_MHZ FLOAT,
    POWER_KW FLOAT,
    ERP_KW FLOAT COMMENT 'Effective Radiated Power',
    COVERAGE_RADIUS_KM FLOAT,
    POPULATION_COVERED INTEGER,
    
    -- License
    LICENSE_NUMBER VARCHAR(50),
    LICENSE_EXPIRY_DATE DATE,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- CLIENT_INSTALLATIONS (Operator equipment on TDF sites - ~20,000)
-- ============================================================================

CREATE OR REPLACE TABLE CLIENT_INSTALLATIONS (
    INSTALLATION_ID VARCHAR(20) PRIMARY KEY,
    SITE_ID VARCHAR(20) NOT NULL REFERENCES SITES(SITE_ID),
    OPERATOR_ID VARCHAR(10) NOT NULL REFERENCES TDF_DATA_PLATFORM.CORE.OPERATORS(OPERATOR_ID),
    
    -- Contract
    CONTRACT_NUMBER VARCHAR(50),
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    CONTRACT_TYPE VARCHAR(30) COMMENT 'COLOCATION, BTS, FULL_SERVICE',
    
    -- Technical
    TECHNOLOGY VARCHAR(20) COMMENT '2G, 3G, 4G, 5G',
    EQUIPMENT_COUNT INTEGER,
    POWER_ALLOCATION_KW FLOAT,
    SPACE_ALLOCATION_M2 FLOAT,
    
    -- Financial
    MONTHLY_FEE_EUR FLOAT,
    ANNUAL_REVENUE_EUR FLOAT,
    
    -- Status
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- FIBRE_NETWORK (5,500 km optical fibre)
-- ============================================================================

CREATE OR REPLACE TABLE FIBRE_NETWORK (
    SEGMENT_ID VARCHAR(20) PRIMARY KEY,
    SEGMENT_CODE VARCHAR(30) NOT NULL,
    
    -- Route
    START_SITE_ID VARCHAR(20) REFERENCES SITES(SITE_ID),
    END_SITE_ID VARCHAR(20) REFERENCES SITES(SITE_ID),
    START_CITY VARCHAR(100),
    END_CITY VARCHAR(100),
    
    -- Technical
    LENGTH_KM FLOAT,
    FIBRE_COUNT INTEGER,
    FIBRE_TYPE VARCHAR(30) COMMENT 'SINGLE_MODE, MULTI_MODE',
    CAPACITY_GBPS FLOAT,
    
    -- Status
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    INSTALLATION_DATE DATE,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- POINTS_OF_SERVICE (Combined view reference - 21,244 PoS/PoP)
-- ============================================================================

CREATE OR REPLACE TABLE POINTS_OF_SERVICE (
    POS_ID VARCHAR(20) PRIMARY KEY,
    SITE_ID VARCHAR(20) NOT NULL REFERENCES SITES(SITE_ID),
    POS_TYPE VARCHAR(30) NOT NULL COMMENT 'TELECOM, BROADCAST, EDGE, INDOOR',
    OPERATOR_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.OPERATORS(OPERATOR_ID),
    SERVICE_TYPE VARCHAR(50),
    
    -- Status
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    ACTIVATION_DATE DATE,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE OR REPLACE INDEX IDX_SITES_DEPARTMENT ON SITES(DEPARTMENT_ID);
CREATE OR REPLACE INDEX IDX_SITES_TYPE ON SITES(SITE_TYPE);
CREATE OR REPLACE INDEX IDX_SITES_STATUS ON SITES(STATUS);
CREATE OR REPLACE INDEX IDX_TOWERS_SITE ON TOWERS(SITE_ID);
CREATE OR REPLACE INDEX IDX_EQUIPMENT_SITE ON EQUIPMENT(SITE_ID);
CREATE OR REPLACE INDEX IDX_EQUIPMENT_STATUS ON EQUIPMENT(LIFECYCLE_STATUS);
CREATE OR REPLACE INDEX IDX_ANTENNAS_SITE ON ANTENNAS(SITE_ID);
CREATE OR REPLACE INDEX IDX_CLIENT_INST_OPERATOR ON CLIENT_INSTALLATIONS(OPERATOR_ID);

SELECT 'INFRASTRUCTURE TABLES CREATED' AS STATUS, CURRENT_TIMESTAMP() AS CREATED_AT;

