-- ============================================================================
-- TDF DATA PLATFORM - HR TABLES
-- ============================================================================
-- Human Resources: Employees, Skills, Workforce Capacity, Diversity Metrics
-- Scale: ~1,500 employees
-- ============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE TDF_WH;
USE DATABASE TDF_DATA_PLATFORM;
USE SCHEMA HR;

-- ============================================================================
-- EMPLOYEES (~1,500 TDF employees)
-- ============================================================================

CREATE OR REPLACE TABLE EMPLOYEES (
    EMPLOYEE_ID VARCHAR(20) PRIMARY KEY,
    EMPLOYEE_CODE VARCHAR(20) NOT NULL UNIQUE,
    
    -- Personal Info
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200),
    PHONE VARCHAR(30),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(10) COMMENT 'M, F, OTHER',
    
    -- Employment
    HIRE_DATE DATE NOT NULL,
    TERMINATION_DATE DATE,
    EMPLOYMENT_TYPE VARCHAR(20) COMMENT 'PERMANENT, CONTRACT, INTERN',
    EMPLOYMENT_STATUS VARCHAR(20) DEFAULT 'ACTIVE' COMMENT 'ACTIVE, ON_LEAVE, TERMINATED',
    
    -- Position
    JOB_TITLE VARCHAR(100),
    JOB_LEVEL VARCHAR(20) COMMENT 'ENTRY, JUNIOR, MID, SENIOR, LEAD, MANAGER, DIRECTOR, VP, C_LEVEL',
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    DEPARTMENT VARCHAR(100),
    COST_CENTER_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.COST_CENTERS(COST_CENTER_ID),
    
    -- Manager
    MANAGER_ID VARCHAR(20) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    
    -- Location
    WORK_LOCATION VARCHAR(100),
    REGION_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.REGIONS(REGION_ID),
    IS_FIELD_WORKER BOOLEAN DEFAULT FALSE,
    IS_REMOTE_ELIGIBLE BOOLEAN DEFAULT FALSE,
    
    -- Compensation (anonymized ranges)
    SALARY_BAND VARCHAR(20) COMMENT 'BAND_1 to BAND_10',
    FTE_PERCENTAGE FLOAT DEFAULT 1.0 COMMENT '1.0 = full time',
    
    -- Audit
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'TDF_HRIS',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- SKILLS (Skill definitions)
-- ============================================================================

CREATE OR REPLACE TABLE SKILLS (
    SKILL_ID VARCHAR(20) PRIMARY KEY,
    SKILL_CODE VARCHAR(30) NOT NULL UNIQUE,
    SKILL_NAME VARCHAR(100) NOT NULL,
    SKILL_CATEGORY_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.SKILL_CATEGORIES(SKILL_CATEGORY_ID),
    
    -- Classification
    SKILL_TYPE VARCHAR(30) COMMENT 'TECHNICAL, SOFT, CERTIFICATION, LANGUAGE',
    IS_CRITICAL BOOLEAN DEFAULT FALSE,
    
    -- Details
    DESCRIPTION VARCHAR(500),
    PROFICIENCY_LEVELS INTEGER DEFAULT 5 COMMENT 'Number of levels (e.g., 1-5)',
    
    -- Demand
    MARKET_DEMAND VARCHAR(20) COMMENT 'HIGH, MEDIUM, LOW',
    INTERNAL_DEMAND VARCHAR(20) COMMENT 'HIGH, MEDIUM, LOW',
    
    -- Audit
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- SKILLS_MATRIX (Employee-Skill mapping)
-- ============================================================================

CREATE OR REPLACE TABLE SKILLS_MATRIX (
    SKILL_MATRIX_ID VARCHAR(20) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(20) NOT NULL REFERENCES EMPLOYEES(EMPLOYEE_ID),
    SKILL_ID VARCHAR(20) NOT NULL REFERENCES SKILLS(SKILL_ID),
    
    -- Proficiency
    PROFICIENCY_LEVEL INTEGER NOT NULL COMMENT '1-5 scale',
    PROFICIENCY_LABEL VARCHAR(20) COMMENT 'BEGINNER, BASIC, INTERMEDIATE, ADVANCED, EXPERT',
    
    -- Certification
    IS_CERTIFIED BOOLEAN DEFAULT FALSE,
    CERTIFICATION_NAME VARCHAR(100),
    CERTIFICATION_DATE DATE,
    CERTIFICATION_EXPIRY DATE,
    
    -- Assessment
    LAST_ASSESSED_DATE DATE,
    ASSESSED_BY VARCHAR(100),
    
    -- Development
    TARGET_PROFICIENCY INTEGER,
    DEVELOPMENT_PLAN VARCHAR(500),
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    UNIQUE (EMPLOYEE_ID, SKILL_ID)
);

-- ============================================================================
-- WORKFORCE_CAPACITY (Monthly capacity planning - UC1)
-- ============================================================================

CREATE OR REPLACE TABLE WORKFORCE_CAPACITY (
    CAPACITY_ID VARCHAR(20) PRIMARY KEY,
    
    -- Period
    YEAR_MONTH DATE NOT NULL COMMENT 'First day of month',
    
    -- Grouping
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    REGION_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.REGIONS(REGION_ID),
    SKILL_CATEGORY_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.SKILL_CATEGORIES(SKILL_CATEGORY_ID),
    JOB_FAMILY VARCHAR(50),
    
    -- Capacity Metrics
    HEADCOUNT INTEGER,
    FTE_AVAILABLE FLOAT COMMENT 'Full-time equivalent available',
    FTE_ALLOCATED FLOAT COMMENT 'FTE already committed to projects',
    FTE_REMAINING FLOAT GENERATED ALWAYS AS (FTE_AVAILABLE - FTE_ALLOCATED) VIRTUAL,
    
    -- Hours
    TOTAL_HOURS_AVAILABLE FLOAT,
    HOURS_PLANNED FLOAT,
    HOURS_ACTUAL FLOAT,
    UTILIZATION_PCT FLOAT,
    
    -- Forecast vs Actual
    IS_FORECAST BOOLEAN DEFAULT FALSE,
    FORECAST_CONFIDENCE VARCHAR(20) COMMENT 'HIGH, MEDIUM, LOW',
    
    -- Audit
    SNAPSHOT_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- DIVERSITY_METRICS (ESG - Gender equality H/F - UC2)
-- ============================================================================

CREATE OR REPLACE TABLE DIVERSITY_METRICS (
    METRIC_ID VARCHAR(20) PRIMARY KEY,
    
    -- Period
    YEAR_MONTH DATE NOT NULL,
    REPORT_TYPE VARCHAR(30) NOT NULL COMMENT 'MONTHLY, QUARTERLY, ANNUAL',
    
    -- Grouping
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    JOB_LEVEL VARCHAR(20),
    
    -- Gender Metrics (H/F - Homme/Femme)
    TOTAL_HEADCOUNT INTEGER,
    MALE_COUNT INTEGER,
    FEMALE_COUNT INTEGER,
    OTHER_COUNT INTEGER,
    FEMALE_PERCENTAGE FLOAT,
    
    -- Management Gender
    MANAGEMENT_TOTAL INTEGER,
    MANAGEMENT_FEMALE INTEGER,
    MANAGEMENT_FEMALE_PCT FLOAT,
    
    -- Pay Equity Index
    PAY_EQUITY_INDEX FLOAT COMMENT '100 = perfect parity',
    
    -- Age Diversity
    AVG_AGE FLOAT,
    AGE_UNDER_30_PCT FLOAT,
    AGE_30_50_PCT FLOAT,
    AGE_OVER_50_PCT FLOAT,
    
    -- Other Metrics
    DISABILITY_PCT FLOAT,
    TRAINING_HOURS_PER_EMPLOYEE FLOAT,
    TURNOVER_RATE FLOAT,
    
    -- ESG Compliance
    EGALITE_INDEX_SCORE INTEGER COMMENT 'French equality index 0-100',
    
    -- Audit
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'TDF_HRIS',
    SOURCE_RECORD_ID VARCHAR(50),
    CALCULATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- TRAINING_RECORDS
-- ============================================================================

CREATE OR REPLACE TABLE TRAINING_RECORDS (
    TRAINING_ID VARCHAR(20) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(20) NOT NULL REFERENCES EMPLOYEES(EMPLOYEE_ID),
    
    -- Training Details
    TRAINING_NAME VARCHAR(200) NOT NULL,
    TRAINING_TYPE VARCHAR(30) COMMENT 'INTERNAL, EXTERNAL, ONLINE, CERTIFICATION',
    SKILL_ID VARCHAR(20) REFERENCES SKILLS(SKILL_ID),
    
    -- Dates
    START_DATE DATE,
    END_DATE DATE,
    DURATION_HOURS FLOAT,
    
    -- Completion
    STATUS VARCHAR(20) COMMENT 'PLANNED, IN_PROGRESS, COMPLETED, CANCELLED',
    COMPLETION_DATE DATE,
    SCORE FLOAT,
    PASSED BOOLEAN,
    
    -- Cost
    COST_EUR FLOAT,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- ABSENCE_RECORDS (For capacity planning)
-- ============================================================================

CREATE OR REPLACE TABLE ABSENCE_RECORDS (
    ABSENCE_ID VARCHAR(20) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(20) NOT NULL REFERENCES EMPLOYEES(EMPLOYEE_ID),
    
    -- Absence Details
    ABSENCE_TYPE VARCHAR(30) NOT NULL COMMENT 'VACATION, SICK, PARENTAL, TRAINING, OTHER',
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    DURATION_DAYS FLOAT,
    
    -- Status
    STATUS VARCHAR(20) COMMENT 'REQUESTED, APPROVED, REJECTED, CANCELLED',
    APPROVED_BY VARCHAR(100),
    
    -- Impact
    IMPACTS_CAPACITY BOOLEAN DEFAULT TRUE,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Note: Snowflake automatically optimizes queries via micro-partitions
-- No explicit indexes needed for standard tables

SELECT 'HR TABLES CREATED' AS STATUS, CURRENT_TIMESTAMP() AS CREATED_AT;

