-- ============================================================================
-- TDF DATA PLATFORM - COMMERCIAL TABLES
-- ============================================================================
-- Commercial: Demand Forecast, Projects, Contracts, Investment Scenarios
-- Supports UC1: Resource & Capacity Planning
-- ============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE TDF_WH;
USE DATABASE TDF_DATA_PLATFORM;
USE SCHEMA COMMERCIAL;

-- ============================================================================
-- DEMAND_FORECAST (18-month rolling forecast - UC1)
-- ============================================================================

CREATE OR REPLACE TABLE DEMAND_FORECAST (
    FORECAST_ID VARCHAR(20) PRIMARY KEY,
    
    -- Period
    FORECAST_DATE DATE NOT NULL COMMENT 'Date when forecast was made',
    TARGET_MONTH DATE NOT NULL COMMENT 'Month being forecasted',
    HORIZON_MONTHS INTEGER COMMENT 'How many months out this forecast is',
    
    -- Grouping
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    REGION_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.REGIONS(REGION_ID),
    SERVICE_TYPE VARCHAR(50) COMMENT 'SITE_HOSTING, BROADCAST, INDOOR, EDGE',
    
    -- Demand Metrics
    DEMAND_FTE FLOAT COMMENT 'Full-time equivalents needed',
    DEMAND_HOURS FLOAT COMMENT 'Work hours required',
    
    -- By Skill Category
    SKILL_CATEGORY_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.SKILL_CATEGORIES(SKILL_CATEGORY_ID),
    
    -- Revenue Driven
    REVENUE_FORECAST_EUR FLOAT,
    COMMERCIAL_CONTRIBUTION_EUR FLOAT COMMENT 'Revenue minus direct costs',
    
    -- Confidence
    FORECAST_TYPE VARCHAR(20) COMMENT 'COMMITTED, PIPELINE, SPECULATIVE',
    CONFIDENCE_PCT INTEGER COMMENT '0-100%',
    
    -- Variance
    PREVIOUS_FORECAST_FTE FLOAT,
    VARIANCE_FTE FLOAT,
    
    -- Audit
    FORECAST_VERSION INTEGER DEFAULT 1,
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- PROJECTS (Active and planned projects)
-- ============================================================================

CREATE OR REPLACE TABLE PROJECTS (
    PROJECT_ID VARCHAR(20) PRIMARY KEY,
    PROJECT_CODE VARCHAR(30) NOT NULL UNIQUE,
    PROJECT_NAME VARCHAR(200) NOT NULL,
    
    -- Classification
    PROJECT_TYPE VARCHAR(50) NOT NULL COMMENT 'NEW_SITE, UPGRADE, MAINTENANCE, DECOMMISSION, ROLLOUT',
    PRIORITY VARCHAR(20) COMMENT 'CRITICAL, HIGH, MEDIUM, LOW',
    
    -- Ownership
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    PROJECT_MANAGER_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.HR.EMPLOYEES(EMPLOYEE_ID),
    SPONSOR VARCHAR(100),
    
    -- Client
    OPERATOR_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.OPERATORS(OPERATOR_ID),
    IS_INTERNAL BOOLEAN DEFAULT FALSE,
    
    -- Location
    REGION_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.REGIONS(REGION_ID),
    SITE_ID VARCHAR(20),
    
    -- Timeline
    PLANNED_START_DATE DATE,
    PLANNED_END_DATE DATE,
    ACTUAL_START_DATE DATE,
    ACTUAL_END_DATE DATE,
    
    -- Status
    STATUS VARCHAR(20) NOT NULL COMMENT 'DRAFT, APPROVED, IN_PROGRESS, ON_HOLD, COMPLETED, CANCELLED',
    PHASE VARCHAR(30) COMMENT 'INITIATION, PLANNING, EXECUTION, CLOSING',
    PCT_COMPLETE FLOAT DEFAULT 0,
    
    -- Resources
    ESTIMATED_FTE FLOAT,
    ESTIMATED_HOURS FLOAT,
    ACTUAL_HOURS FLOAT,
    
    -- Budget
    BUDGET_EUR FLOAT,
    ACTUAL_COST_EUR FLOAT,
    BUDGET_VARIANCE_EUR FLOAT,
    
    -- Revenue
    EXPECTED_REVENUE_EUR FLOAT,
    COMMERCIAL_CONTRIBUTION_EUR FLOAT,
    
    -- Risk
    RISK_LEVEL VARCHAR(20) COMMENT 'LOW, MEDIUM, HIGH, CRITICAL',
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- PROJECT_RESOURCE_REQUIREMENTS
-- ============================================================================

CREATE OR REPLACE TABLE PROJECT_RESOURCE_REQUIREMENTS (
    REQUIREMENT_ID VARCHAR(20) PRIMARY KEY,
    PROJECT_ID VARCHAR(20) NOT NULL REFERENCES PROJECTS(PROJECT_ID),
    
    -- Resource Need
    SKILL_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.HR.SKILLS(SKILL_ID),
    SKILL_CATEGORY_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.SKILL_CATEGORIES(SKILL_CATEGORY_ID),
    JOB_ROLE VARCHAR(100),
    
    -- Quantity
    FTE_REQUIRED FLOAT,
    HOURS_REQUIRED FLOAT,
    MIN_PROFICIENCY_LEVEL INTEGER,
    
    -- Period
    START_DATE DATE,
    END_DATE DATE,
    
    -- Status
    IS_FILLED BOOLEAN DEFAULT FALSE,
    ASSIGNED_EMPLOYEE_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.HR.EMPLOYEES(EMPLOYEE_ID),
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- CONTRACTS (Client contracts)
-- ============================================================================

CREATE OR REPLACE TABLE CONTRACTS (
    CONTRACT_ID VARCHAR(20) PRIMARY KEY,
    CONTRACT_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    CONTRACT_NAME VARCHAR(200),
    
    -- Parties
    OPERATOR_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.OPERATORS(OPERATOR_ID),
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    
    -- Type
    CONTRACT_TYPE VARCHAR(30) COMMENT 'MASTER_AGREEMENT, SITE_LEASE, SERVICE, MAINTENANCE',
    SERVICE_TYPE VARCHAR(50),
    
    -- Duration
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    AUTO_RENEWAL BOOLEAN DEFAULT FALSE,
    NOTICE_PERIOD_DAYS INTEGER,
    
    -- Financial
    ANNUAL_VALUE_EUR FLOAT,
    TOTAL_CONTRACT_VALUE_EUR FLOAT,
    PAYMENT_TERMS_DAYS INTEGER,
    IS_INDEXED BOOLEAN DEFAULT TRUE COMMENT '>90% of TDF contracts are indexed',
    INDEX_TYPE VARCHAR(30) COMMENT 'CPI, ILAT, CUSTOM',
    
    -- Status
    STATUS VARCHAR(20) COMMENT 'DRAFT, ACTIVE, EXPIRING, EXPIRED, TERMINATED',
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- INVESTMENT_SCENARIOS (C-Level what-if analysis)
-- ============================================================================

CREATE OR REPLACE TABLE INVESTMENT_SCENARIOS (
    SCENARIO_ID VARCHAR(20) PRIMARY KEY,
    SCENARIO_NAME VARCHAR(200) NOT NULL,
    SCENARIO_TYPE VARCHAR(30) COMMENT 'CAPEX_DEFERRAL, COVERAGE_EXPANSION, COST_REDUCTION',
    
    -- Description
    DESCRIPTION VARCHAR(1000),
    ASSUMPTIONS VARCHAR(2000),
    
    -- Parameters
    TIME_HORIZON_YEARS INTEGER,
    BASE_YEAR INTEGER,
    
    -- Financial Impact
    CAPEX_CHANGE_EUR FLOAT,
    OPEX_CHANGE_EUR FLOAT,
    REVENUE_IMPACT_EUR FLOAT,
    NPV_EUR FLOAT,
    IRR_PCT FLOAT,
    PAYBACK_YEARS FLOAT,
    
    -- Risk
    RISK_ASSESSMENT VARCHAR(500),
    PROBABILITY_PCT INTEGER,
    
    -- Status
    STATUS VARCHAR(20) COMMENT 'DRAFT, UNDER_REVIEW, APPROVED, REJECTED',
    CREATED_BY VARCHAR(100),
    APPROVED_BY VARCHAR(100),
    APPROVAL_DATE DATE,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- CLIENT_PIPELINE (Sales pipeline for market context)
-- ============================================================================

CREATE OR REPLACE TABLE CLIENT_PIPELINE (
    PIPELINE_ID VARCHAR(20) PRIMARY KEY,
    
    -- Opportunity
    OPPORTUNITY_NAME VARCHAR(200) NOT NULL,
    OPERATOR_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.OPERATORS(OPERATOR_ID),
    
    -- Classification
    OPPORTUNITY_TYPE VARCHAR(50) COMMENT 'NEW_SITES, EXPANSION, UPGRADE, RENEWAL',
    SERVICE_TYPE VARCHAR(50),
    
    -- Location
    REGION_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.REGIONS(REGION_ID),
    SITE_COUNT INTEGER COMMENT 'Number of sites involved',
    
    -- Value
    ESTIMATED_VALUE_EUR FLOAT,
    ANNUAL_REVENUE_EUR FLOAT,
    
    -- Timeline
    EXPECTED_CLOSE_DATE DATE,
    EXPECTED_START_DATE DATE,
    
    -- Stage
    PIPELINE_STAGE VARCHAR(30) COMMENT 'LEAD, QUALIFIED, PROPOSAL, NEGOTIATION, CLOSED_WON, CLOSED_LOST',
    PROBABILITY_PCT INTEGER,
    WEIGHTED_VALUE_EUR FLOAT GENERATED ALWAYS AS (ESTIMATED_VALUE_EUR * PROBABILITY_PCT / 100) VIRTUAL,
    
    -- Owner
    SALES_OWNER_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.HR.EMPLOYEES(EMPLOYEE_ID),
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Note: Snowflake automatically optimizes queries via micro-partitions
-- No explicit indexes needed for standard tables

SELECT 'COMMERCIAL TABLES CREATED' AS STATUS, CURRENT_TIMESTAMP() AS CREATED_AT;

