-- ============================================================================
-- TDF DATA PLATFORM - OPERATIONS TABLES
-- ============================================================================
-- Operations: Work Orders, Maintenance, Resource Allocation, Broadcast Coverage
-- Supports UC1, UC3, UC4
-- ============================================================================

USE DATABASE TDF_DATA_PLATFORM;
USE SCHEMA OPERATIONS;

-- ============================================================================
-- WORK_ORDERS (Field work requiring resources - UC1)
-- ============================================================================

CREATE OR REPLACE TABLE WORK_ORDERS (
    WORK_ORDER_ID VARCHAR(20) PRIMARY KEY,
    WORK_ORDER_NUMBER VARCHAR(30) NOT NULL UNIQUE,
    
    -- Classification
    WORK_ORDER_TYPE VARCHAR(30) NOT NULL COMMENT 'MAINTENANCE, INSTALLATION, REPAIR, INSPECTION, DECOMMISSION',
    PRIORITY VARCHAR(20) NOT NULL COMMENT 'EMERGENCY, HIGH, MEDIUM, LOW',
    CATEGORY VARCHAR(50) COMMENT 'PREVENTIVE, CORRECTIVE, UPGRADE',
    
    -- Location
    SITE_ID VARCHAR(20) NOT NULL REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES(SITE_ID),
    TOWER_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.TOWERS(TOWER_ID),
    EQUIPMENT_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.EQUIPMENT(EQUIPMENT_ID),
    REGION_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.REGIONS(REGION_ID),
    
    -- Description
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(2000),
    
    -- Ownership
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    OPERATOR_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.OPERATORS(OPERATOR_ID),
    
    -- Timeline
    CREATED_DATE DATE NOT NULL,
    SCHEDULED_START DATE,
    SCHEDULED_END DATE,
    ACTUAL_START DATE,
    ACTUAL_END DATE,
    DUE_DATE DATE,
    
    -- Status
    STATUS VARCHAR(20) NOT NULL COMMENT 'OPEN, ASSIGNED, IN_PROGRESS, ON_HOLD, COMPLETED, CANCELLED',
    
    -- Resources
    ESTIMATED_HOURS FLOAT,
    ACTUAL_HOURS FLOAT,
    REQUIRED_SKILL_IDS VARCHAR(500) COMMENT 'Comma-separated skill IDs',
    ASSIGNED_TEAM VARCHAR(100),
    LEAD_TECHNICIAN_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.HR.EMPLOYEES(EMPLOYEE_ID),
    
    -- Cost
    ESTIMATED_COST_EUR FLOAT,
    ACTUAL_COST_EUR FLOAT,
    MATERIAL_COST_EUR FLOAT,
    LABOR_COST_EUR FLOAT,
    
    -- Completion
    COMPLETION_NOTES VARCHAR(2000),
    FOLLOW_UP_REQUIRED BOOLEAN DEFAULT FALSE,
    
    -- SLA
    SLA_TARGET_HOURS FLOAT,
    SLA_MET BOOLEAN,
    
    -- Audit
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'TDF_CMMS',
    SOURCE_RECORD_ID VARCHAR(50),
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- RESOURCE_ALLOCATION (Staff-to-project/work order assignments - UC1)
-- ============================================================================

CREATE OR REPLACE TABLE RESOURCE_ALLOCATION (
    ALLOCATION_ID VARCHAR(20) PRIMARY KEY,
    
    -- Employee
    EMPLOYEE_ID VARCHAR(20) NOT NULL REFERENCES TDF_DATA_PLATFORM.HR.EMPLOYEES(EMPLOYEE_ID),
    
    -- Assignment Target (one of these)
    PROJECT_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.COMMERCIAL.PROJECTS(PROJECT_ID),
    WORK_ORDER_ID VARCHAR(20) REFERENCES WORK_ORDERS(WORK_ORDER_ID),
    
    -- Period
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    
    -- Allocation
    FTE_ALLOCATED FLOAT COMMENT 'Portion of FTE (0.0-1.0)',
    HOURS_ALLOCATED FLOAT,
    
    -- Role
    ROLE_ON_ASSIGNMENT VARCHAR(100),
    IS_LEAD BOOLEAN DEFAULT FALSE,
    
    -- Status
    STATUS VARCHAR(20) COMMENT 'PLANNED, CONFIRMED, ACTIVE, COMPLETED, CANCELLED',
    
    -- Actual
    HOURS_WORKED FLOAT,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- MAINTENANCE_RECORDS (Equipment maintenance history - UC4)
-- ============================================================================

CREATE OR REPLACE TABLE MAINTENANCE_RECORDS (
    MAINTENANCE_ID VARCHAR(20) PRIMARY KEY,
    
    -- Related
    WORK_ORDER_ID VARCHAR(20) REFERENCES WORK_ORDERS(WORK_ORDER_ID),
    EQUIPMENT_ID VARCHAR(20) NOT NULL REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.EQUIPMENT(EQUIPMENT_ID),
    SITE_ID VARCHAR(20) NOT NULL REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES(SITE_ID),
    
    -- Type
    MAINTENANCE_TYPE VARCHAR(30) NOT NULL COMMENT 'PREVENTIVE, CORRECTIVE, PREDICTIVE, EMERGENCY',
    
    -- Description
    DESCRIPTION VARCHAR(2000),
    ISSUE_FOUND VARCHAR(1000),
    RESOLUTION VARCHAR(1000),
    
    -- Dates
    SCHEDULED_DATE DATE,
    PERFORMED_DATE DATE NOT NULL,
    
    -- Performed By
    TECHNICIAN_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.HR.EMPLOYEES(EMPLOYEE_ID),
    TECHNICIAN_NAME VARCHAR(100),
    CONTRACTOR_NAME VARCHAR(100),
    
    -- Duration
    DURATION_HOURS FLOAT,
    DOWNTIME_HOURS FLOAT,
    
    -- Parts
    PARTS_REPLACED VARCHAR(500),
    PARTS_COST_EUR FLOAT,
    LABOR_COST_EUR FLOAT,
    TOTAL_COST_EUR FLOAT,
    
    -- Outcome
    CONDITION_BEFORE VARCHAR(20) COMMENT 'GOOD, FAIR, POOR, CRITICAL',
    CONDITION_AFTER VARCHAR(20),
    NEXT_MAINTENANCE_DATE DATE,
    
    -- Audit
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'TDF_CMMS',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- EQUIPMENT_STATUS (Current equipment health/condition - UC4)
-- ============================================================================

CREATE OR REPLACE TABLE EQUIPMENT_STATUS (
    STATUS_ID VARCHAR(20) PRIMARY KEY,
    EQUIPMENT_ID VARCHAR(20) NOT NULL REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.EQUIPMENT(EQUIPMENT_ID),
    
    -- Status Date
    STATUS_DATE DATE NOT NULL,
    
    -- Current Status
    OPERATIONAL_STATUS VARCHAR(20) NOT NULL COMMENT 'OPERATIONAL, DEGRADED, FAILED, OFFLINE, MAINTENANCE',
    
    -- Condition
    CONDITION_SCORE INTEGER COMMENT '0-100, higher is better',
    CONDITION_LABEL VARCHAR(20) COMMENT 'EXCELLENT, GOOD, FAIR, POOR, CRITICAL',
    
    -- Risk
    FAILURE_RISK_SCORE INTEGER COMMENT '0-100, higher is riskier',
    FAILURE_PROBABILITY_30D FLOAT COMMENT 'Probability of failure in next 30 days',
    
    -- Performance
    PERFORMANCE_SCORE INTEGER COMMENT '0-100',
    UPTIME_PCT_30D FLOAT COMMENT 'Uptime percentage last 30 days',
    
    -- Alerts
    HAS_ACTIVE_ALERTS BOOLEAN DEFAULT FALSE,
    ALERT_COUNT INTEGER DEFAULT 0,
    LAST_ALERT_DATE TIMESTAMP_NTZ,
    
    -- Maintenance
    DAYS_SINCE_LAST_MAINTENANCE INTEGER,
    DAYS_UNTIL_NEXT_MAINTENANCE INTEGER,
    MAINTENANCE_OVERDUE BOOLEAN DEFAULT FALSE,
    
    -- Lifecycle
    REMAINING_LIFE_YEARS FLOAT,
    RECOMMENDED_ACTION VARCHAR(50) COMMENT 'NONE, MONITOR, MAINTENANCE, REPLACE_SOON, REPLACE_NOW',
    
    -- Audit
    SNAPSHOT_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- BROADCAST_COVERAGE (Population coverage % for broadcast sites)
-- ============================================================================

CREATE OR REPLACE TABLE BROADCAST_COVERAGE (
    COVERAGE_ID VARCHAR(20) PRIMARY KEY,
    
    -- Site/Transmitter
    SITE_ID VARCHAR(20) NOT NULL REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES(SITE_ID),
    TRANSMITTER_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.BROADCAST_TRANSMITTERS(TRANSMITTER_ID),
    
    -- Period
    MEASUREMENT_DATE DATE NOT NULL,
    
    -- Broadcast Type
    BROADCAST_TYPE VARCHAR(20) NOT NULL COMMENT 'DTT, FM_RADIO, DAB_PLUS',
    SERVICE_NAME VARCHAR(100),
    
    -- Coverage Metrics
    COVERAGE_AREA_KM2 FLOAT,
    POPULATION_COVERED INTEGER,
    POPULATION_COVERAGE_PCT FLOAT,
    HOUSEHOLDS_COVERED INTEGER,
    
    -- Quality
    SIGNAL_QUALITY_SCORE INTEGER COMMENT '0-100',
    RECEPTION_COMPLAINTS INTEGER,
    
    -- Regional Breakdown
    REGION_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.REGIONS(REGION_ID),
    DEPARTMENT_COVERAGE_PCT FLOAT,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- INCIDENTS (Operational incidents)
-- ============================================================================

CREATE OR REPLACE TABLE INCIDENTS (
    INCIDENT_ID VARCHAR(20) PRIMARY KEY,
    INCIDENT_NUMBER VARCHAR(30) NOT NULL UNIQUE,
    
    -- Classification
    INCIDENT_TYPE VARCHAR(30) NOT NULL COMMENT 'OUTAGE, DEGRADATION, SECURITY, ENVIRONMENTAL',
    SEVERITY VARCHAR(20) NOT NULL COMMENT 'CRITICAL, MAJOR, MINOR, WARNING',
    
    -- Location
    SITE_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES(SITE_ID),
    EQUIPMENT_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.EQUIPMENT(EQUIPMENT_ID),
    
    -- Description
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(2000),
    ROOT_CAUSE VARCHAR(1000),
    
    -- Impact
    SERVICES_AFFECTED VARCHAR(500),
    CUSTOMERS_AFFECTED INTEGER,
    REVENUE_IMPACT_EUR FLOAT,
    
    -- Timeline
    DETECTED_AT TIMESTAMP_NTZ NOT NULL,
    ACKNOWLEDGED_AT TIMESTAMP_NTZ,
    RESOLVED_AT TIMESTAMP_NTZ,
    DURATION_MINUTES INTEGER,
    
    -- Status
    STATUS VARCHAR(20) NOT NULL COMMENT 'OPEN, INVESTIGATING, RESOLVING, RESOLVED, CLOSED',
    
    -- Resolution
    RESOLUTION_NOTES VARCHAR(2000),
    WORK_ORDER_ID VARCHAR(20) REFERENCES WORK_ORDERS(WORK_ORDER_ID),
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE OR REPLACE INDEX IDX_WO_SITE ON WORK_ORDERS(SITE_ID);
CREATE OR REPLACE INDEX IDX_WO_STATUS ON WORK_ORDERS(STATUS);
CREATE OR REPLACE INDEX IDX_WO_TYPE ON WORK_ORDERS(WORK_ORDER_TYPE);
CREATE OR REPLACE INDEX IDX_ALLOCATION_EMP ON RESOURCE_ALLOCATION(EMPLOYEE_ID);
CREATE OR REPLACE INDEX IDX_MAINT_EQUIPMENT ON MAINTENANCE_RECORDS(EQUIPMENT_ID);
CREATE OR REPLACE INDEX IDX_EQUIP_STATUS_DATE ON EQUIPMENT_STATUS(STATUS_DATE);
CREATE OR REPLACE INDEX IDX_INCIDENTS_SITE ON INCIDENTS(SITE_ID);

SELECT 'OPERATIONS TABLES CREATED' AS STATUS, CURRENT_TIMESTAMP() AS CREATED_AT;

