-- ============================================================================
-- TDF DATA PLATFORM - FINANCE TABLES
-- ============================================================================
-- Finance: CAPEX, Budgets, Accounting Entries, Revenue by Segment
-- Based on TDF 2024 Financials: EUR 799.1M Revenue, 42-53% EBITDAaL
-- Supports UC2 (ESG Audit), UC4 (CAPEX/Lifecycle)
-- ============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE TDF_WH;
USE DATABASE TDF_DATA_PLATFORM;
USE SCHEMA FINANCE;

-- ============================================================================
-- REVENUE_BY_SEGMENT (TDF Revenue Structure - EUR 799.1M)
-- ============================================================================

CREATE OR REPLACE TABLE REVENUE_BY_SEGMENT (
    REVENUE_ID VARCHAR(20) PRIMARY KEY,
    
    -- Period
    FISCAL_YEAR INTEGER NOT NULL,
    FISCAL_MONTH INTEGER NOT NULL,
    PERIOD_DATE DATE NOT NULL,
    
    -- Segment Hierarchy
    SEGMENT_LEVEL1 VARCHAR(50) NOT NULL COMMENT 'BROADCAST, TELECOMS, CONNECTIVITY_EDGE, OTHER',
    SEGMENT_LEVEL2 VARCHAR(50) COMMENT 'DTT, RADIO, SITE_HOSTING, OTHER_TELECOM, INDOOR, EDGE_CONNECT, PMN',
    
    -- Revenue
    REVENUE_EUR FLOAT NOT NULL,
    REVENUE_PRIOR_YEAR_EUR FLOAT,
    REVENUE_YOY_GROWTH_PCT FLOAT,
    
    -- Target
    REVENUE_TARGET_EUR FLOAT,
    VARIANCE_TO_TARGET_EUR FLOAT,
    VARIANCE_TO_TARGET_PCT FLOAT,
    
    -- Indexation (>90% indexed)
    INDEXED_REVENUE_PCT FLOAT DEFAULT 0.92,
    
    -- Grouping
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    REGION_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.REGIONS(REGION_ID),
    
    -- Audit
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'TDF_ERP',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- REVENUE_BY_CLIENT (Operator revenue breakdown)
-- ============================================================================

CREATE OR REPLACE TABLE REVENUE_BY_CLIENT (
    REVENUE_CLIENT_ID VARCHAR(20) PRIMARY KEY,
    
    -- Period
    FISCAL_YEAR INTEGER NOT NULL,
    FISCAL_MONTH INTEGER NOT NULL,
    PERIOD_DATE DATE NOT NULL,
    
    -- Client
    OPERATOR_ID VARCHAR(15) NOT NULL REFERENCES TDF_DATA_PLATFORM.CORE.OPERATORS(OPERATOR_ID),
    
    -- Revenue
    REVENUE_EUR FLOAT NOT NULL,
    REVENUE_PRIOR_YEAR_EUR FLOAT,
    REVENUE_SHARE_PCT FLOAT COMMENT 'Share of total telecom revenue',
    
    -- Services
    SITE_HOSTING_REVENUE_EUR FLOAT,
    OTHER_SERVICES_REVENUE_EUR FLOAT,
    
    -- Sites
    ACTIVE_SITES INTEGER,
    NEW_SITES_IN_PERIOD INTEGER,
    
    -- Client Concentration Risk
    IS_TOP_10_CLIENT BOOLEAN DEFAULT FALSE,
    CONCENTRATION_RISK VARCHAR(20) COMMENT 'LOW, MEDIUM, HIGH',
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- CAPEX_BUDGET (Annual CAPEX budget by category - UC4)
-- ============================================================================

CREATE OR REPLACE TABLE CAPEX_BUDGET (
    BUDGET_ID VARCHAR(20) PRIMARY KEY,
    
    -- Period
    FISCAL_YEAR INTEGER NOT NULL,
    BUDGET_VERSION VARCHAR(20) COMMENT 'INITIAL, REVISED_Q1, REVISED_Q2, FINAL',
    
    -- Category
    CAPEX_CATEGORY VARCHAR(50) NOT NULL COMMENT 'GROWTH, MAINTENANCE, DIGITALIZATION',
    CAPEX_SUBCATEGORY VARCHAR(50) COMMENT 'NEW_TOWERS, UPGRADES, REPLACEMENTS, IT_SYSTEMS',
    
    -- Budget Amounts
    BUDGET_EUR FLOAT NOT NULL,
    BUDGET_PRIOR_YEAR_EUR FLOAT,
    
    -- Allocation
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    REGION_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.REGIONS(REGION_ID),
    
    -- TDF Ratios (from investor presentation)
    -- Growth CAPEX ~61%, Maintenance ~8% of revenue
    CATEGORY_PCT_OF_TOTAL FLOAT,
    
    -- Approval
    APPROVED_BY VARCHAR(100),
    APPROVAL_DATE DATE,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- CAPEX_ACTUALS (Actual CAPEX spend vs budget - UC4)
-- ============================================================================

CREATE OR REPLACE TABLE CAPEX_ACTUALS (
    ACTUAL_ID VARCHAR(20) PRIMARY KEY,
    
    -- Period
    FISCAL_YEAR INTEGER NOT NULL,
    FISCAL_MONTH INTEGER NOT NULL,
    PERIOD_DATE DATE NOT NULL,
    
    -- Category
    CAPEX_CATEGORY VARCHAR(50) NOT NULL,
    CAPEX_SUBCATEGORY VARCHAR(50),
    
    -- Amounts
    ACTUAL_EUR FLOAT NOT NULL,
    CUMULATIVE_YTD_EUR FLOAT,
    
    -- Budget Comparison
    BUDGET_ID VARCHAR(20) REFERENCES CAPEX_BUDGET(BUDGET_ID),
    BUDGET_EUR FLOAT,
    VARIANCE_EUR FLOAT,
    VARIANCE_PCT FLOAT,
    
    -- Forecast
    FULL_YEAR_FORECAST_EUR FLOAT,
    
    -- Grouping
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    REGION_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.REGIONS(REGION_ID),
    
    -- Related Assets
    SITE_ID VARCHAR(20),
    PROJECT_ID VARCHAR(20),
    
    -- Audit
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'TDF_ERP',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- ACCOUNTING_ENTRIES (Journal entries with full lineage - UC2 ESG Audit)
-- ============================================================================

CREATE OR REPLACE TABLE ACCOUNTING_ENTRIES (
    ENTRY_ID VARCHAR(20) PRIMARY KEY,
    JOURNAL_ID VARCHAR(30) NOT NULL,
    LINE_NUMBER INTEGER NOT NULL,
    
    -- Period
    POSTING_DATE DATE NOT NULL,
    FISCAL_YEAR INTEGER NOT NULL,
    FISCAL_PERIOD INTEGER NOT NULL,
    
    -- Account
    GL_ACCOUNT VARCHAR(20) NOT NULL,
    GL_ACCOUNT_NAME VARCHAR(100),
    ACCOUNT_TYPE VARCHAR(20) COMMENT 'ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE',
    
    -- Amount
    DEBIT_EUR FLOAT DEFAULT 0,
    CREDIT_EUR FLOAT DEFAULT 0,
    NET_AMOUNT_EUR FLOAT,  -- Computed: DEBIT_EUR - CREDIT_EUR
    
    -- Dimensions
    COST_CENTER_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.COST_CENTERS(COST_CENTER_ID),
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    PROJECT_ID VARCHAR(20),
    SITE_ID VARCHAR(20),
    
    -- Description
    DESCRIPTION VARCHAR(500),
    REFERENCE_NUMBER VARCHAR(50),
    
    -- Document
    DOCUMENT_TYPE VARCHAR(30) COMMENT 'INVOICE, PAYMENT, JOURNAL, ACCRUAL',
    DOCUMENT_NUMBER VARCHAR(50),
    DOCUMENT_DATE DATE,
    VENDOR_CUSTOMER_ID VARCHAR(20),
    VENDOR_CUSTOMER_NAME VARCHAR(200),
    
    -- ESG AUDIT TRAIL - Critical for UC2
    SOURCE_SYSTEM VARCHAR(50) NOT NULL DEFAULT 'TDF_ERP',
    SOURCE_MODULE VARCHAR(50) COMMENT 'AP, AR, GL, FA',
    SOURCE_RECORD_ID VARCHAR(50) NOT NULL,
    SOURCE_BATCH_ID VARCHAR(50),
    
    -- Audit Trail
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    APPROVED_BY VARCHAR(100),
    APPROVED_AT TIMESTAMP_NTZ,
    
    -- Flags
    IS_POSTED BOOLEAN DEFAULT TRUE,
    IS_REVERSED BOOLEAN DEFAULT FALSE,
    REVERSAL_ENTRY_ID VARCHAR(20),
    IS_ESG_RELEVANT BOOLEAN DEFAULT FALSE COMMENT 'Flag for ESG reporting',
    
    UNIQUE (JOURNAL_ID, LINE_NUMBER)
);

-- ============================================================================
-- RENEWAL_FORECAST (Equipment replacement predictions - UC4)
-- ============================================================================

CREATE OR REPLACE TABLE RENEWAL_FORECAST (
    FORECAST_ID VARCHAR(20) PRIMARY KEY,
    
    -- Equipment
    EQUIPMENT_ID VARCHAR(20) NOT NULL REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.EQUIPMENT(EQUIPMENT_ID),
    SITE_ID VARCHAR(20) NOT NULL,
    
    -- Forecast Date
    FORECAST_DATE DATE NOT NULL,
    
    -- Replacement Prediction
    PREDICTED_REPLACEMENT_DATE DATE,
    REPLACEMENT_YEAR INTEGER,
    REPLACEMENT_QUARTER VARCHAR(6),
    CONFIDENCE_PCT FLOAT,
    
    -- Cost Estimates
    REPLACEMENT_COST_EUR FLOAT,
    INSTALLATION_COST_EUR FLOAT,
    TOTAL_COST_EUR FLOAT,
    
    -- Factors
    AGE_YEARS FLOAT,
    CONDITION_SCORE INTEGER,
    FAILURE_RISK_SCORE INTEGER,
    MAINTENANCE_COST_TREND VARCHAR(20) COMMENT 'INCREASING, STABLE, DECREASING',
    
    -- Priority
    REPLACEMENT_PRIORITY VARCHAR(20) COMMENT 'CRITICAL, HIGH, MEDIUM, LOW',
    RECOMMENDED_ACTION VARCHAR(100),
    
    -- Budget Impact
    BUDGET_YEAR INTEGER,
    IN_CURRENT_BUDGET BOOLEAN DEFAULT FALSE,
    
    -- Audit
    MODEL_VERSION VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- EBITDA_METRICS (Key financial metrics for executives)
-- ============================================================================

CREATE OR REPLACE TABLE EBITDA_METRICS (
    METRIC_ID VARCHAR(20) PRIMARY KEY,
    
    -- Period
    FISCAL_YEAR INTEGER NOT NULL,
    FISCAL_MONTH INTEGER NOT NULL,
    PERIOD_DATE DATE NOT NULL,
    
    -- Revenue
    REVENUE_EUR FLOAT,
    ENERGY_PASSTHROUGH_EUR FLOAT COMMENT 'Energy re-invoiced to customers',
    NET_REVENUE_EUR FLOAT,
    
    -- Costs
    OPEX_EUR FLOAT,
    PERSONNEL_COST_EUR FLOAT,
    ENERGY_COST_EUR FLOAT,
    MAINTENANCE_COST_EUR FLOAT,
    OTHER_OPEX_EUR FLOAT,
    
    -- EBITDA
    EBITDA_EUR FLOAT,
    EBITDA_MARGIN_PCT FLOAT,
    
    -- Adjusted (EBITDAaL)
    LEASE_COST_EUR FLOAT,
    EBITDAAL_EUR FLOAT,
    EBITDAAL_MARGIN_PCT FLOAT COMMENT 'Target: 42-53%',
    
    -- Comparison
    PRIOR_YEAR_EBITDAAL_EUR FLOAT,
    YOY_GROWTH_PCT FLOAT,
    
    -- Grouping
    BU_ID VARCHAR(10) REFERENCES TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS(BU_ID),
    
    -- Status
    TRAFFIC_LIGHT VARCHAR(10) COMMENT 'GREEN, AMBER, RED',
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Note: Snowflake automatically optimizes queries via micro-partitions
-- No explicit indexes needed for standard tables

SELECT 'FINANCE TABLES CREATED' AS STATUS, CURRENT_TIMESTAMP() AS CREATED_AT;

