-- ============================================================================
-- TDF DATA PLATFORM - ESG TABLES
-- ============================================================================
-- ESG: Regulatory Reports, Audit Trails, Board Scorecard
-- Supports UC2: Audited Regulatory Reporting (ESG, Carbon, H/F Equality)
-- Fitch Rating: BBB- (stable)
-- ============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE TDF_WH;
USE DATABASE TDF_DATA_PLATFORM;
USE SCHEMA ESG;

-- ============================================================================
-- REGULATORY_REPORTS (Generated report metadata)
-- ============================================================================

CREATE OR REPLACE TABLE REGULATORY_REPORTS (
    REPORT_ID VARCHAR(20) PRIMARY KEY,
    REPORT_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    
    -- Report Type
    REPORT_TYPE VARCHAR(50) NOT NULL COMMENT 'ESG_ANNUAL, CARBON_FOOTPRINT, EQUALITY_INDEX, CSRD, TAXONOMY',
    REPORT_NAME VARCHAR(200) NOT NULL,
    REPORTING_FRAMEWORK VARCHAR(50) COMMENT 'GRI, SASB, TCFD, CSRD, FRENCH_LAW',
    
    -- Period
    REPORTING_YEAR INTEGER NOT NULL,
    REPORTING_PERIOD VARCHAR(20) COMMENT 'ANNUAL, H1, H2, Q1, Q2, Q3, Q4',
    PERIOD_START_DATE DATE,
    PERIOD_END_DATE DATE,
    
    -- Status
    STATUS VARCHAR(20) NOT NULL COMMENT 'DRAFT, REVIEW, APPROVED, PUBLISHED, ARCHIVED',
    
    -- Approval Chain
    PREPARED_BY VARCHAR(100),
    PREPARED_DATE DATE,
    REVIEWED_BY VARCHAR(100),
    REVIEW_DATE DATE,
    APPROVED_BY VARCHAR(100),
    APPROVAL_DATE DATE,
    
    -- Publication
    PUBLICATION_DATE DATE,
    PUBLICATION_LOCATION VARCHAR(500),
    
    -- External Audit
    IS_AUDITED BOOLEAN DEFAULT FALSE,
    AUDITOR_NAME VARCHAR(100),
    AUDIT_OPINION VARCHAR(50) COMMENT 'UNQUALIFIED, QUALIFIED, ADVERSE, DISCLAIMER',
    AUDIT_DATE DATE,
    AUDIT_REPORT_NUMBER VARCHAR(50),
    
    -- Key Metrics (summary)
    CARBON_EMISSIONS_TONNES FLOAT,
    RENEWABLE_ENERGY_PCT FLOAT,
    EQUALITY_INDEX_SCORE INTEGER,
    
    -- Storage
    DOCUMENT_PATH VARCHAR(500),
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- AUDIT_TRAIL (Complete data lineage for auditors - UC2)
-- ============================================================================

CREATE OR REPLACE TABLE AUDIT_TRAIL (
    AUDIT_ID VARCHAR(20) PRIMARY KEY,
    
    -- Report Reference
    REPORT_ID VARCHAR(20) REFERENCES REGULATORY_REPORTS(REPORT_ID),
    
    -- What was audited
    METRIC_NAME VARCHAR(100) NOT NULL,
    METRIC_VALUE VARCHAR(100),
    METRIC_UNIT VARCHAR(50),
    
    -- Data Lineage - Critical for ESG Audit
    SOURCE_SCHEMA VARCHAR(50) NOT NULL,
    SOURCE_TABLE VARCHAR(100) NOT NULL,
    SOURCE_COLUMN VARCHAR(100),
    SOURCE_QUERY VARCHAR(4000),
    
    -- Granularity
    AGGREGATION_LEVEL VARCHAR(50) COMMENT 'SITE, REGION, BU, COMPANY',
    AGGREGATION_METHOD VARCHAR(50) COMMENT 'SUM, AVG, COUNT, WEIGHTED_AVG',
    
    -- Time Reference
    DATA_PERIOD_START DATE,
    DATA_PERIOD_END DATE,
    DATA_EXTRACTION_DATE TIMESTAMP_NTZ,
    
    -- Transformation
    TRANSFORMATION_APPLIED VARCHAR(1000),
    CALCULATION_FORMULA VARCHAR(1000),
    EMISSION_FACTOR_USED FLOAT,
    EMISSION_FACTOR_SOURCE VARCHAR(200),
    
    -- Data Quality
    RECORD_COUNT INTEGER,
    NULL_COUNT INTEGER,
    ESTIMATED_DATA_PCT FLOAT,
    DATA_QUALITY_SCORE INTEGER COMMENT '0-100',
    
    -- Verification
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    VERIFIED_BY VARCHAR(100),
    VERIFICATION_DATE DATE,
    VERIFICATION_NOTES VARCHAR(1000),
    
    -- Issues
    HAS_DATA_ISSUES BOOLEAN DEFAULT FALSE,
    ISSUE_DESCRIPTION VARCHAR(1000),
    ISSUE_RESOLUTION VARCHAR(1000),
    
    -- Audit
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- BOARD_SCORECARD (ESG metrics for C-Level/Board)
-- ============================================================================

CREATE OR REPLACE TABLE BOARD_SCORECARD (
    SCORECARD_ID VARCHAR(20) PRIMARY KEY,
    
    -- Period
    REPORTING_DATE DATE NOT NULL,
    FISCAL_YEAR INTEGER NOT NULL,
    REPORTING_PERIOD VARCHAR(20),
    
    -- Environmental (E)
    CARBON_EMISSIONS_TONNES FLOAT,
    CARBON_INTENSITY_KG_EUR FLOAT COMMENT 'kg CO2e per EUR revenue',
    CARBON_REDUCTION_PCT FLOAT COMMENT 'vs baseline year',
    RENEWABLE_ENERGY_PCT FLOAT,
    ENERGY_EFFICIENCY_IMPROVEMENT_PCT FLOAT,
    
    -- Social (S)
    TOTAL_EMPLOYEES INTEGER,
    FEMALE_EMPLOYEES_PCT FLOAT,
    FEMALE_MANAGEMENT_PCT FLOAT,
    EQUALITY_INDEX_SCORE INTEGER COMMENT 'French index 0-100',
    TRAINING_HOURS_PER_EMPLOYEE FLOAT,
    EMPLOYEE_SATISFACTION_SCORE FLOAT,
    ACCIDENT_FREQUENCY_RATE FLOAT,
    TURNOVER_RATE FLOAT,
    
    -- Governance (G)
    BOARD_INDEPENDENCE_PCT FLOAT,
    BOARD_FEMALE_PCT FLOAT,
    ETHICS_TRAINING_COMPLETION_PCT FLOAT,
    SUPPLIER_CODE_ADHERENCE_PCT FLOAT,
    
    -- Targets & Variance
    CARBON_TARGET_TONNES FLOAT,
    CARBON_VARIANCE_PCT FLOAT,
    RENEWABLE_TARGET_PCT FLOAT,
    RENEWABLE_VARIANCE_PCT FLOAT,
    EQUALITY_TARGET_SCORE INTEGER,
    EQUALITY_VARIANCE INTEGER,
    
    -- Status Indicators
    ENVIRONMENTAL_STATUS VARCHAR(10) COMMENT 'GREEN, AMBER, RED',
    SOCIAL_STATUS VARCHAR(10),
    GOVERNANCE_STATUS VARCHAR(10),
    OVERALL_ESG_STATUS VARCHAR(10),
    
    -- Rating
    EXTERNAL_ESG_RATING VARCHAR(20),
    RATING_AGENCY VARCHAR(50),
    FITCH_CREDIT_RATING VARCHAR(10) DEFAULT 'BBB-',
    
    -- Commentary
    EXECUTIVE_SUMMARY VARCHAR(2000),
    KEY_ACHIEVEMENTS VARCHAR(1000),
    KEY_CHALLENGES VARCHAR(1000),
    ACTION_ITEMS VARCHAR(1000),
    
    -- Audit
    PREPARED_BY VARCHAR(100),
    APPROVED_BY VARCHAR(100),
    APPROVAL_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- ESG_TARGETS (Annual and long-term targets)
-- ============================================================================

CREATE OR REPLACE TABLE ESG_TARGETS (
    TARGET_ID VARCHAR(20) PRIMARY KEY,
    
    -- Target Definition
    TARGET_NAME VARCHAR(200) NOT NULL,
    TARGET_CATEGORY VARCHAR(50) NOT NULL COMMENT 'ENVIRONMENTAL, SOCIAL, GOVERNANCE',
    METRIC_NAME VARCHAR(100) NOT NULL,
    METRIC_UNIT VARCHAR(50),
    
    -- Timeline
    BASELINE_YEAR INTEGER,
    BASELINE_VALUE FLOAT,
    TARGET_YEAR INTEGER,
    TARGET_VALUE FLOAT,
    
    -- Interim Milestones
    MILESTONE_2025 FLOAT,
    MILESTONE_2030 FLOAT,
    MILESTONE_2050 FLOAT,
    
    -- Current Progress
    CURRENT_VALUE FLOAT,
    CURRENT_YEAR INTEGER,
    PROGRESS_PCT FLOAT,
    ON_TRACK VARCHAR(20) COMMENT 'ON_TRACK, AT_RISK, OFF_TRACK',
    
    -- Science-Based
    IS_SCIENCE_BASED BOOLEAN DEFAULT FALSE,
    SBT_VALIDATED BOOLEAN DEFAULT FALSE,
    
    -- Commitment
    COMMITMENT_TYPE VARCHAR(50) COMMENT 'REGULATORY, VOLUNTARY, SBTI, NET_ZERO',
    PUBLIC_COMMITMENT BOOLEAN DEFAULT TRUE,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- COMPLIANCE_REQUIREMENTS (Regulatory compliance tracking)
-- ============================================================================

CREATE OR REPLACE TABLE COMPLIANCE_REQUIREMENTS (
    REQUIREMENT_ID VARCHAR(20) PRIMARY KEY,
    
    -- Regulation
    REGULATION_NAME VARCHAR(200) NOT NULL,
    REGULATION_TYPE VARCHAR(50) COMMENT 'EU, FRENCH, INDUSTRY',
    REGULATION_CODE VARCHAR(50),
    
    -- Applicability
    APPLIES_TO_TDF BOOLEAN DEFAULT TRUE,
    EFFECTIVE_DATE DATE,
    COMPLIANCE_DEADLINE DATE,
    
    -- Requirements
    REQUIREMENT_DESCRIPTION VARCHAR(2000),
    REPORTING_FREQUENCY VARCHAR(20),
    
    -- Compliance Status
    COMPLIANCE_STATUS VARCHAR(20) COMMENT 'COMPLIANT, PARTIAL, NON_COMPLIANT, NOT_APPLICABLE',
    LAST_ASSESSMENT_DATE DATE,
    NEXT_ASSESSMENT_DATE DATE,
    
    -- Evidence
    EVIDENCE_REQUIRED VARCHAR(1000),
    EVIDENCE_LOCATION VARCHAR(500),
    
    -- Risk
    NON_COMPLIANCE_RISK VARCHAR(20) COMMENT 'HIGH, MEDIUM, LOW',
    POTENTIAL_PENALTY_EUR FLOAT,
    
    -- Owner
    COMPLIANCE_OWNER VARCHAR(100),
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE OR REPLACE INDEX IDX_REPORTS_YEAR ON REGULATORY_REPORTS(REPORTING_YEAR);
CREATE OR REPLACE INDEX IDX_REPORTS_TYPE ON REGULATORY_REPORTS(REPORT_TYPE);
CREATE OR REPLACE INDEX IDX_AUDIT_REPORT ON AUDIT_TRAIL(REPORT_ID);
CREATE OR REPLACE INDEX IDX_AUDIT_SOURCE ON AUDIT_TRAIL(SOURCE_SCHEMA, SOURCE_TABLE);
CREATE OR REPLACE INDEX IDX_SCORECARD_DATE ON BOARD_SCORECARD(REPORTING_DATE);
CREATE OR REPLACE INDEX IDX_TARGETS_CATEGORY ON ESG_TARGETS(TARGET_CATEGORY);

SELECT 'ESG TABLES CREATED' AS STATUS, CURRENT_TIMESTAMP() AS CREATED_AT;

