-- ============================================================================
-- TDF DATA PLATFORM - DIGITAL TWIN TABLES
-- ============================================================================
-- Digital Twin: Asset Models, Discrepancy Detection, Validation Rules
-- Supports UC3: Infrastructure Data Mastery & Digital Twin Quality
-- Scale: 21,244 Points of Service, >2,000 pylons in 3D models
-- ============================================================================

USE DATABASE TDF_DATA_PLATFORM;
USE SCHEMA DIGITAL_TWIN;

-- ============================================================================
-- ASSET_MODELS (3D model references for Digital Twin)
-- ============================================================================

CREATE OR REPLACE TABLE ASSET_MODELS (
    MODEL_ID VARCHAR(20) PRIMARY KEY,
    
    -- Asset Reference
    SITE_ID VARCHAR(20) NOT NULL REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES(SITE_ID),
    TOWER_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.TOWERS(TOWER_ID),
    EQUIPMENT_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.EQUIPMENT(EQUIPMENT_ID),
    
    -- Model Type
    MODEL_TYPE VARCHAR(30) NOT NULL COMMENT 'SITE_3D, TOWER_3D, EQUIPMENT, FLOOR_PLAN, NETWORK_DIAGRAM',
    MODEL_FORMAT VARCHAR(20) COMMENT 'IFC, GLTF, OBJ, DWG, PDF',
    
    -- Model Details
    MODEL_NAME VARCHAR(200),
    MODEL_VERSION VARCHAR(20),
    MODEL_PATH VARCHAR(500),
    THUMBNAIL_PATH VARCHAR(500),
    
    -- Geometry
    BOUNDING_BOX_JSON VARCHAR(2000) COMMENT 'JSON with min/max coordinates',
    COORDINATE_SYSTEM VARCHAR(50) COMMENT 'WGS84, LAMBERT93, etc.',
    LOD_LEVEL INTEGER COMMENT 'Level of Detail 1-5',
    
    -- Source
    CREATED_FROM VARCHAR(50) COMMENT 'SURVEY, LIDAR, PHOTOGRAMMETRY, CAD, MANUAL',
    SURVEY_DATE DATE,
    SURVEYOR_NAME VARCHAR(100),
    
    -- Quality
    ACCURACY_CM FLOAT COMMENT 'Positional accuracy in cm',
    COMPLETENESS_PCT FLOAT COMMENT 'Data completeness percentage',
    QUALITY_SCORE INTEGER COMMENT '0-100',
    
    -- Status
    STATUS VARCHAR(20) NOT NULL COMMENT 'DRAFT, VALIDATED, PUBLISHED, DEPRECATED',
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    
    -- Sync Status with Physical World
    LAST_SYNC_DATE TIMESTAMP_NTZ,
    SYNC_STATUS VARCHAR(20) COMMENT 'SYNCED, PENDING, DISCREPANCY',
    
    -- Audit
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- ASSET_MODEL_ATTRIBUTES (Attributes stored in Digital Twin)
-- ============================================================================

CREATE OR REPLACE TABLE ASSET_MODEL_ATTRIBUTES (
    ATTRIBUTE_ID VARCHAR(20) PRIMARY KEY,
    MODEL_ID VARCHAR(20) NOT NULL REFERENCES ASSET_MODELS(MODEL_ID),
    
    -- Attribute Definition
    ATTRIBUTE_NAME VARCHAR(100) NOT NULL,
    ATTRIBUTE_TYPE VARCHAR(30) COMMENT 'STRING, NUMBER, DATE, BOOLEAN, GEOMETRY',
    ATTRIBUTE_VALUE VARCHAR(1000),
    ATTRIBUTE_UNIT VARCHAR(30),
    
    -- Source
    SOURCE_SYSTEM VARCHAR(50),
    SOURCE_FIELD VARCHAR(100),
    
    -- Comparison with Physical Data
    PHYSICAL_VALUE VARCHAR(1000) COMMENT 'Value from asset management system',
    VALUES_MATCH BOOLEAN,
    
    -- Audit
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- DISCREPANCY_LOG (Model vs Reality gaps - UC3)
-- ============================================================================

CREATE OR REPLACE TABLE DISCREPANCY_LOG (
    DISCREPANCY_ID VARCHAR(20) PRIMARY KEY,
    
    -- Asset Reference
    MODEL_ID VARCHAR(20) REFERENCES ASSET_MODELS(MODEL_ID),
    SITE_ID VARCHAR(20) NOT NULL REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES(SITE_ID),
    TOWER_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.TOWERS(TOWER_ID),
    EQUIPMENT_ID VARCHAR(20) REFERENCES TDF_DATA_PLATFORM.INFRASTRUCTURE.EQUIPMENT(EQUIPMENT_ID),
    
    -- Discrepancy Details
    DISCREPANCY_TYPE VARCHAR(50) NOT NULL COMMENT 'MISSING_ASSET, EXTRA_ASSET, WRONG_POSITION, WRONG_ATTRIBUTE, OUTDATED',
    SEVERITY VARCHAR(20) NOT NULL COMMENT 'CRITICAL, HIGH, MEDIUM, LOW',
    
    -- Description
    FIELD_NAME VARCHAR(100),
    EXPECTED_VALUE VARCHAR(500) COMMENT 'Value in Digital Twin',
    ACTUAL_VALUE VARCHAR(500) COMMENT 'Value in physical/source system',
    DESCRIPTION VARCHAR(1000),
    
    -- Detection
    DETECTED_DATE DATE NOT NULL,
    DETECTED_BY VARCHAR(50) COMMENT 'AUTOMATED, FIELD_INSPECTION, DATA_COMPARE',
    DETECTION_SOURCE VARCHAR(100),
    
    -- Impact
    IMPACT_DESCRIPTION VARCHAR(500),
    AFFECTS_OPERATIONS BOOLEAN DEFAULT FALSE,
    AFFECTS_BILLING BOOLEAN DEFAULT FALSE,
    AFFECTS_COMPLIANCE BOOLEAN DEFAULT FALSE,
    
    -- Resolution
    STATUS VARCHAR(20) NOT NULL COMMENT 'OPEN, INVESTIGATING, RESOLVED, WONT_FIX',
    RESOLUTION_NOTES VARCHAR(1000),
    RESOLVED_DATE DATE,
    RESOLVED_BY VARCHAR(100),
    RESOLUTION_ACTION VARCHAR(50) COMMENT 'UPDATE_MODEL, UPDATE_PHYSICAL, BOTH, NO_ACTION',
    
    -- Tracking
    WORK_ORDER_ID VARCHAR(20),
    DAYS_OPEN INTEGER,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- VALIDATION_RULES (Data quality rules for Digital Twin)
-- ============================================================================

CREATE OR REPLACE TABLE VALIDATION_RULES (
    RULE_ID VARCHAR(20) PRIMARY KEY,
    RULE_CODE VARCHAR(30) NOT NULL UNIQUE,
    RULE_NAME VARCHAR(200) NOT NULL,
    
    -- Scope
    APPLIES_TO_SCHEMA VARCHAR(50),
    APPLIES_TO_TABLE VARCHAR(100),
    APPLIES_TO_COLUMN VARCHAR(100),
    
    -- Rule Definition
    RULE_TYPE VARCHAR(30) COMMENT 'COMPLETENESS, ACCURACY, CONSISTENCY, TIMELINESS, UNIQUENESS',
    RULE_DESCRIPTION VARCHAR(1000),
    RULE_SQL VARCHAR(4000) COMMENT 'SQL to identify violations',
    
    -- Thresholds
    THRESHOLD_VALUE FLOAT,
    THRESHOLD_OPERATOR VARCHAR(10) COMMENT 'GT, GTE, LT, LTE, EQ, NEQ',
    
    -- Severity
    SEVERITY_IF_FAILED VARCHAR(20) COMMENT 'CRITICAL, HIGH, MEDIUM, LOW',
    
    -- Status
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    
    -- Schedule
    RUN_FREQUENCY VARCHAR(20) COMMENT 'REALTIME, HOURLY, DAILY, WEEKLY',
    LAST_RUN_DATE TIMESTAMP_NTZ,
    NEXT_RUN_DATE TIMESTAMP_NTZ,
    
    -- Audit
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- VALIDATION_RESULTS (Results of validation rule execution)
-- ============================================================================

CREATE OR REPLACE TABLE VALIDATION_RESULTS (
    RESULT_ID VARCHAR(20) PRIMARY KEY,
    RULE_ID VARCHAR(20) NOT NULL REFERENCES VALIDATION_RULES(RULE_ID),
    
    -- Execution
    RUN_DATE TIMESTAMP_NTZ NOT NULL,
    RUN_DURATION_SECONDS FLOAT,
    
    -- Results
    STATUS VARCHAR(20) NOT NULL COMMENT 'PASSED, FAILED, ERROR',
    TOTAL_RECORDS_CHECKED INTEGER,
    RECORDS_PASSED INTEGER,
    RECORDS_FAILED INTEGER,
    PASS_RATE_PCT FLOAT,
    
    -- Score
    QUALITY_SCORE INTEGER COMMENT '0-100',
    THRESHOLD_MET BOOLEAN,
    
    -- Failed Records (sample)
    SAMPLE_FAILED_RECORDS VARCHAR(4000) COMMENT 'JSON array of sample failures',
    
    -- Trend
    PRIOR_RUN_PASS_RATE FLOAT,
    TREND VARCHAR(20) COMMENT 'IMPROVING, STABLE, DEGRADING',
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- DATA_QUALITY_SCORES (Aggregated quality scores per entity)
-- ============================================================================

CREATE OR REPLACE TABLE DATA_QUALITY_SCORES (
    SCORE_ID VARCHAR(20) PRIMARY KEY,
    
    -- Scope
    ENTITY_TYPE VARCHAR(30) NOT NULL COMMENT 'SITE, TOWER, EQUIPMENT, REGION, COMPANY',
    ENTITY_ID VARCHAR(20),
    
    -- Period
    SCORE_DATE DATE NOT NULL,
    
    -- Dimension Scores (0-100)
    COMPLETENESS_SCORE INTEGER,
    ACCURACY_SCORE INTEGER,
    CONSISTENCY_SCORE INTEGER,
    TIMELINESS_SCORE INTEGER,
    UNIQUENESS_SCORE INTEGER,
    
    -- Overall Score
    OVERALL_SCORE INTEGER,
    SCORE_LABEL VARCHAR(20) COMMENT 'EXCELLENT, GOOD, FAIR, POOR, CRITICAL',
    
    -- Comparisons
    PRIOR_PERIOD_SCORE INTEGER,
    SCORE_CHANGE INTEGER,
    TARGET_SCORE INTEGER,
    MEETS_TARGET BOOLEAN,
    
    -- Issues
    OPEN_DISCREPANCIES INTEGER,
    CRITICAL_ISSUES INTEGER,
    
    -- Audit
    CALCULATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- SYNC_HISTORY (Synchronization history between systems)
-- ============================================================================

CREATE OR REPLACE TABLE SYNC_HISTORY (
    SYNC_ID VARCHAR(20) PRIMARY KEY,
    
    -- Sync Details
    SYNC_TYPE VARCHAR(30) COMMENT 'FULL, INCREMENTAL, DELTA',
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    TARGET_SYSTEM VARCHAR(50) NOT NULL DEFAULT 'DIGITAL_TWIN',
    
    -- Timing
    START_TIME TIMESTAMP_NTZ NOT NULL,
    END_TIME TIMESTAMP_NTZ,
    DURATION_SECONDS FLOAT,
    
    -- Scope
    ENTITY_TYPE VARCHAR(30),
    RECORDS_PROCESSED INTEGER,
    RECORDS_CREATED INTEGER,
    RECORDS_UPDATED INTEGER,
    RECORDS_DELETED INTEGER,
    RECORDS_FAILED INTEGER,
    
    -- Status
    STATUS VARCHAR(20) NOT NULL COMMENT 'RUNNING, COMPLETED, FAILED, PARTIAL',
    ERROR_MESSAGE VARCHAR(2000),
    
    -- Quality
    DISCREPANCIES_FOUND INTEGER,
    DISCREPANCIES_RESOLVED INTEGER,
    
    -- Audit
    TRIGGERED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE OR REPLACE INDEX IDX_MODELS_SITE ON ASSET_MODELS(SITE_ID);
CREATE OR REPLACE INDEX IDX_MODELS_STATUS ON ASSET_MODELS(STATUS);
CREATE OR REPLACE INDEX IDX_DISCREPANCY_SITE ON DISCREPANCY_LOG(SITE_ID);
CREATE OR REPLACE INDEX IDX_DISCREPANCY_STATUS ON DISCREPANCY_LOG(STATUS);
CREATE OR REPLACE INDEX IDX_DISCREPANCY_SEVERITY ON DISCREPANCY_LOG(SEVERITY);
CREATE OR REPLACE INDEX IDX_QUALITY_ENTITY ON DATA_QUALITY_SCORES(ENTITY_TYPE, ENTITY_ID);
CREATE OR REPLACE INDEX IDX_QUALITY_DATE ON DATA_QUALITY_SCORES(SCORE_DATE);

SELECT 'DIGITAL TWIN TABLES CREATED' AS STATUS, CURRENT_TIMESTAMP() AS CREATED_AT;

