-- ============================================================================
-- TDF DATA PLATFORM - ANALYTICS VIEWS
-- ============================================================================
-- Operational dashboard views for all 4 use cases
-- Pre-built queries optimized for dashboard consumption
-- ============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE TDF_WH;
USE DATABASE TDF_DATA_PLATFORM;
USE SCHEMA ANALYTICS;

-- ============================================================================
-- UC1: RESOURCE & CAPACITY PLANNING VIEWS
-- ============================================================================

-- Capacity vs Demand Summary
CREATE OR REPLACE VIEW VW_CAPACITY_VS_DEMAND AS
SELECT 
    wc.YEAR_MONTH,
    wc.BU_ID,
    bu.BU_NAME,
    wc.REGION_ID,
    r.REGION_NAME,
    wc.SKILL_CATEGORY_ID,
    sc.SKILL_CATEGORY_NAME,
    
    -- Capacity
    wc.HEADCOUNT,
    wc.FTE_AVAILABLE,
    wc.FTE_ALLOCATED,
    wc.FTE_REMAINING,
    
    -- Demand
    COALESCE(df.DEMAND_FTE, 0) AS DEMAND_FTE,
    COALESCE(df.REVENUE_FORECAST_EUR, 0) AS REVENUE_FORECAST_EUR,
    
    -- Gap Analysis
    wc.FTE_REMAINING - COALESCE(df.DEMAND_FTE, 0) AS FTE_GAP,
    CASE 
        WHEN wc.FTE_REMAINING >= COALESCE(df.DEMAND_FTE, 0) THEN 'SUFFICIENT'
        WHEN wc.FTE_REMAINING >= COALESCE(df.DEMAND_FTE, 0) * 0.8 THEN 'TIGHT'
        ELSE 'SHORTAGE'
    END AS CAPACITY_STATUS,
    
    -- Utilization
    ROUND(wc.FTE_ALLOCATED / NULLIF(wc.FTE_AVAILABLE, 0) * 100, 1) AS UTILIZATION_PCT
    
FROM TDF_DATA_PLATFORM.HR.WORKFORCE_CAPACITY wc
LEFT JOIN TDF_DATA_PLATFORM.COMMERCIAL.DEMAND_FORECAST df 
    ON wc.YEAR_MONTH = df.TARGET_MONTH 
    AND wc.BU_ID = df.BU_ID 
    AND wc.REGION_ID = df.REGION_ID
    AND wc.SKILL_CATEGORY_ID = df.SKILL_CATEGORY_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS bu ON wc.BU_ID = bu.BU_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.REGIONS r ON wc.REGION_ID = r.REGION_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.SKILL_CATEGORIES sc ON wc.SKILL_CATEGORY_ID = sc.SKILL_CATEGORY_ID;

-- Work Order Backlog
CREATE OR REPLACE VIEW VW_WORK_ORDER_BACKLOG AS
SELECT 
    wo.REGION_ID,
    r.REGION_NAME,
    wo.BU_ID,
    bu.BU_NAME,
    wo.WORK_ORDER_TYPE,
    wo.PRIORITY,
    wo.STATUS,
    COUNT(*) AS WO_COUNT,
    SUM(wo.ESTIMATED_HOURS) AS TOTAL_ESTIMATED_HOURS,
    SUM(CASE WHEN wo.DUE_DATE < CURRENT_DATE() THEN 1 ELSE 0 END) AS OVERDUE_COUNT,
    AVG(DATEDIFF(DAY, wo.CREATED_DATE, COALESCE(wo.ACTUAL_END, CURRENT_DATE()))) AS AVG_DAYS_TO_COMPLETE
FROM TDF_DATA_PLATFORM.OPERATIONS.WORK_ORDERS wo
LEFT JOIN TDF_DATA_PLATFORM.CORE.REGIONS r ON wo.REGION_ID = r.REGION_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS bu ON wo.BU_ID = bu.BU_ID
GROUP BY wo.REGION_ID, r.REGION_NAME, wo.BU_ID, bu.BU_NAME, wo.WORK_ORDER_TYPE, wo.PRIORITY, wo.STATUS;

-- ============================================================================
-- UC2: ESG REPORTING VIEWS
-- ============================================================================

-- ESG Dashboard Summary
CREATE OR REPLACE VIEW VW_ESG_DASHBOARD AS
SELECT 
    bs.REPORTING_DATE,
    bs.FISCAL_YEAR,
    
    -- Environmental
    bs.CARBON_EMISSIONS_TONNES,
    bs.CARBON_INTENSITY_KG_EUR,
    bs.RENEWABLE_ENERGY_PCT,
    bs.CARBON_TARGET_TONNES,
    bs.CARBON_VARIANCE_PCT,
    bs.ENVIRONMENTAL_STATUS,
    
    -- Social
    bs.TOTAL_EMPLOYEES,
    bs.FEMALE_EMPLOYEES_PCT,
    bs.FEMALE_MANAGEMENT_PCT,
    bs.EQUALITY_INDEX_SCORE,
    bs.TRAINING_HOURS_PER_EMPLOYEE,
    bs.SOCIAL_STATUS,
    
    -- Governance
    bs.BOARD_INDEPENDENCE_PCT,
    bs.BOARD_FEMALE_PCT,
    bs.GOVERNANCE_STATUS,
    
    -- Overall
    bs.OVERALL_ESG_STATUS,
    bs.FITCH_CREDIT_RATING
    
FROM TDF_DATA_PLATFORM.ESG.BOARD_SCORECARD bs;

-- Carbon Emissions by Region
CREATE OR REPLACE VIEW VW_CARBON_BY_REGION AS
SELECT 
    ce.YEAR_MONTH,
    ce.REGION_ID,
    r.REGION_NAME,
    ce.EMISSION_SCOPE,
    SUM(ce.EMISSIONS_TONNES_CO2E) AS TOTAL_EMISSIONS_TONNES,
    SUM(ce.REVENUE_EUR) AS TOTAL_REVENUE_EUR,
    AVG(ce.CARBON_INTENSITY_KG_EUR) AS AVG_CARBON_INTENSITY
FROM TDF_DATA_PLATFORM.ENERGY.CARBON_EMISSIONS ce
LEFT JOIN TDF_DATA_PLATFORM.CORE.REGIONS r ON ce.REGION_ID = r.REGION_ID
GROUP BY ce.YEAR_MONTH, ce.REGION_ID, r.REGION_NAME, ce.EMISSION_SCOPE;

-- Energy Consumption Trends
CREATE OR REPLACE VIEW VW_ENERGY_TRENDS AS
SELECT 
    cr.YEAR_MONTH,
    s.SITE_TYPE,
    r.REGION_NAME,
    COUNT(DISTINCT cr.SITE_ID) AS SITE_COUNT,
    SUM(cr.CONSUMPTION_KWH) AS TOTAL_CONSUMPTION_KWH,
    AVG(cr.CONSUMPTION_KWH) AS AVG_CONSUMPTION_PER_SITE,
    SUM(cr.ENERGY_COST_EUR) AS TOTAL_COST_EUR,
    SUM(cr.PASSTHROUGH_AMOUNT_EUR) AS TOTAL_PASSTHROUGH_EUR
FROM TDF_DATA_PLATFORM.ENERGY.CONSUMPTION_READINGS cr
LEFT JOIN TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES s ON cr.SITE_ID = s.SITE_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.REGIONS r ON s.DEPARTMENT_ID = r.REGION_ID
GROUP BY cr.YEAR_MONTH, s.SITE_TYPE, r.REGION_NAME;

-- ============================================================================
-- UC3: INFRASTRUCTURE & DIGITAL TWIN VIEWS
-- ============================================================================

-- Infrastructure Health Summary
CREATE OR REPLACE VIEW VW_INFRASTRUCTURE_HEALTH AS
SELECT 
    s.SITE_TYPE,
    s.STATUS,
    d.DEPARTMENT_NAME,
    r.REGION_NAME,
    COUNT(*) AS SITE_COUNT,
    AVG(s.CURRENT_TENANTS) AS AVG_TENANTS,
    AVG(s.COLOCATION_RATE) AS AVG_COLOCATION_RATE,
    AVG(s.RISK_SCORE) AS AVG_RISK_SCORE,
    SUM(CASE WHEN s.DIGITAL_TWIN_STATUS = 'SYNCED' THEN 1 ELSE 0 END) AS DT_SYNCED_COUNT,
    SUM(CASE WHEN s.DIGITAL_TWIN_STATUS = 'DISCREPANCY' THEN 1 ELSE 0 END) AS DT_DISCREPANCY_COUNT
FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES s
LEFT JOIN TDF_DATA_PLATFORM.CORE.DEPARTMENTS d ON s.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.REGIONS r ON d.REGION_ID = r.REGION_ID
GROUP BY s.SITE_TYPE, s.STATUS, d.DEPARTMENT_NAME, r.REGION_NAME;

-- Colocation Analysis (TDF rates: Overall 3.9x, MNO 1.8x)
CREATE OR REPLACE VIEW VW_COLOCATION_ANALYSIS AS
SELECT 
    s.SITE_TYPE,
    r.REGION_NAME,
    COUNT(DISTINCT s.SITE_ID) AS TOTAL_SITES,
    SUM(s.MAX_TENANTS) AS TOTAL_CAPACITY,
    SUM(s.CURRENT_TENANTS) AS TOTAL_TENANTS,
    ROUND(SUM(s.CURRENT_TENANTS) / NULLIF(COUNT(DISTINCT s.SITE_ID), 0), 2) AS COLOCATION_RATE,
    SUM(ci.ANNUAL_REVENUE_EUR) AS TOTAL_ANNUAL_REVENUE
FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES s
LEFT JOIN TDF_DATA_PLATFORM.INFRASTRUCTURE.CLIENT_INSTALLATIONS ci ON s.SITE_ID = ci.SITE_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.DEPARTMENTS d ON s.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.REGIONS r ON d.REGION_ID = r.REGION_ID
WHERE s.STATUS = 'ACTIVE'
GROUP BY s.SITE_TYPE, r.REGION_NAME;

-- Digital Twin Quality Score
CREATE OR REPLACE VIEW VW_DIGITAL_TWIN_QUALITY AS
SELECT 
    dqs.SCORE_DATE,
    dqs.ENTITY_TYPE,
    dqs.OVERALL_SCORE,
    dqs.COMPLETENESS_SCORE,
    dqs.ACCURACY_SCORE,
    dqs.CONSISTENCY_SCORE,
    dqs.SCORE_LABEL,
    dqs.OPEN_DISCREPANCIES,
    dqs.CRITICAL_ISSUES,
    dqs.MEETS_TARGET
FROM TDF_DATA_PLATFORM.DIGITAL_TWIN.DATA_QUALITY_SCORES dqs
WHERE dqs.ENTITY_TYPE = 'COMPANY';

-- Discrepancy Summary
CREATE OR REPLACE VIEW VW_DISCREPANCY_SUMMARY AS
SELECT 
    dl.STATUS,
    dl.SEVERITY,
    dl.DISCREPANCY_TYPE,
    COUNT(*) AS DISCREPANCY_COUNT,
    AVG(dl.DAYS_OPEN) AS AVG_DAYS_OPEN,
    SUM(CASE WHEN dl.AFFECTS_OPERATIONS THEN 1 ELSE 0 END) AS AFFECTING_OPERATIONS,
    SUM(CASE WHEN dl.AFFECTS_BILLING THEN 1 ELSE 0 END) AS AFFECTING_BILLING
FROM TDF_DATA_PLATFORM.DIGITAL_TWIN.DISCREPANCY_LOG dl
GROUP BY dl.STATUS, dl.SEVERITY, dl.DISCREPANCY_TYPE;

-- ============================================================================
-- UC4: CAPEX & LIFECYCLE VIEWS
-- ============================================================================

-- Equipment Lifecycle Summary
CREATE OR REPLACE VIEW VW_EQUIPMENT_LIFECYCLE AS
SELECT 
    e.LIFECYCLE_STATUS,
    e.EQUIPMENT_CATEGORY,
    et.EQUIPMENT_TYPE_NAME,
    COUNT(*) AS EQUIPMENT_COUNT,
    AVG(e.AGE_YEARS) AS AVG_AGE_YEARS,
    AVG(e.CONDITION_SCORE) AS AVG_CONDITION_SCORE,
    AVG(e.FAILURE_RISK_SCORE) AS AVG_RISK_SCORE,
    SUM(e.REPLACEMENT_COST_EUR) AS TOTAL_REPLACEMENT_COST,
    SUM(CASE WHEN e.EXPECTED_END_OF_LIFE < CURRENT_DATE() THEN 1 ELSE 0 END) AS PAST_END_OF_LIFE_COUNT
FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.EQUIPMENT e
LEFT JOIN TDF_DATA_PLATFORM.CORE.EQUIPMENT_TYPES et ON e.EQUIPMENT_TYPE_ID = et.EQUIPMENT_TYPE_ID
GROUP BY e.LIFECYCLE_STATUS, e.EQUIPMENT_CATEGORY, et.EQUIPMENT_TYPE_NAME;

-- CAPEX Budget vs Actual
CREATE OR REPLACE VIEW VW_CAPEX_BUDGET_VS_ACTUAL AS
SELECT 
    cb.FISCAL_YEAR,
    cb.CAPEX_CATEGORY,
    cb.CAPEX_SUBCATEGORY,
    bu.BU_NAME,
    cb.BUDGET_EUR,
    COALESCE(SUM(ca.CUMULATIVE_YTD_EUR), 0) AS ACTUAL_YTD_EUR,
    cb.BUDGET_EUR - COALESCE(SUM(ca.CUMULATIVE_YTD_EUR), 0) AS REMAINING_EUR,
    ROUND(COALESCE(SUM(ca.CUMULATIVE_YTD_EUR), 0) / NULLIF(cb.BUDGET_EUR, 0) * 100, 1) AS UTILIZED_PCT,
    CASE 
        WHEN COALESCE(SUM(ca.CUMULATIVE_YTD_EUR), 0) > cb.BUDGET_EUR * 1.1 THEN 'OVER_BUDGET'
        WHEN COALESCE(SUM(ca.CUMULATIVE_YTD_EUR), 0) > cb.BUDGET_EUR * 0.9 THEN 'ON_TRACK'
        ELSE 'UNDER_UTILIZED'
    END AS BUDGET_STATUS
FROM TDF_DATA_PLATFORM.FINANCE.CAPEX_BUDGET cb
LEFT JOIN TDF_DATA_PLATFORM.FINANCE.CAPEX_ACTUALS ca 
    ON cb.FISCAL_YEAR = ca.FISCAL_YEAR 
    AND cb.CAPEX_CATEGORY = ca.CAPEX_CATEGORY
    AND cb.BU_ID = ca.BU_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS bu ON cb.BU_ID = bu.BU_ID
GROUP BY cb.FISCAL_YEAR, cb.CAPEX_CATEGORY, cb.CAPEX_SUBCATEGORY, bu.BU_NAME, cb.BUDGET_EUR;

-- Renewal Forecast Summary
CREATE OR REPLACE VIEW VW_RENEWAL_FORECAST_SUMMARY AS
SELECT 
    rf.REPLACEMENT_YEAR,
    e.EQUIPMENT_CATEGORY,
    rf.REPLACEMENT_PRIORITY,
    COUNT(*) AS EQUIPMENT_COUNT,
    SUM(rf.TOTAL_COST_EUR) AS TOTAL_REPLACEMENT_COST,
    AVG(rf.AGE_YEARS) AS AVG_AGE_YEARS,
    AVG(rf.CONDITION_SCORE) AS AVG_CONDITION_SCORE,
    AVG(rf.CONFIDENCE_PCT) AS AVG_CONFIDENCE_PCT,
    SUM(CASE WHEN rf.IN_CURRENT_BUDGET THEN rf.TOTAL_COST_EUR ELSE 0 END) AS BUDGETED_COST,
    SUM(CASE WHEN NOT rf.IN_CURRENT_BUDGET THEN rf.TOTAL_COST_EUR ELSE 0 END) AS UNBUDGETED_COST
FROM TDF_DATA_PLATFORM.FINANCE.RENEWAL_FORECAST rf
LEFT JOIN TDF_DATA_PLATFORM.INFRASTRUCTURE.EQUIPMENT e ON rf.EQUIPMENT_ID = e.EQUIPMENT_ID
GROUP BY rf.REPLACEMENT_YEAR, e.EQUIPMENT_CATEGORY, rf.REPLACEMENT_PRIORITY;

-- Equipment at Risk (High failure probability)
CREATE OR REPLACE VIEW VW_EQUIPMENT_AT_RISK AS
SELECT 
    e.EQUIPMENT_ID,
    e.EQUIPMENT_CODE,
    e.EQUIPMENT_CATEGORY,
    e.SITE_ID,
    s.SITE_NAME,
    r.REGION_NAME,
    e.INSTALLATION_DATE,
    e.AGE_YEARS,
    e.LIFECYCLE_STATUS,
    es.CONDITION_SCORE,
    es.FAILURE_RISK_SCORE,
    es.FAILURE_PROBABILITY_30D,
    es.RECOMMENDED_ACTION,
    e.REPLACEMENT_COST_EUR,
    e.IS_CRITICAL
FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.EQUIPMENT e
LEFT JOIN TDF_DATA_PLATFORM.OPERATIONS.EQUIPMENT_STATUS es ON e.EQUIPMENT_ID = es.EQUIPMENT_ID
LEFT JOIN TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES s ON e.SITE_ID = s.SITE_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.DEPARTMENTS d ON s.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.REGIONS r ON d.REGION_ID = r.REGION_ID
WHERE es.FAILURE_RISK_SCORE >= 70
   OR es.RECOMMENDED_ACTION IN ('REPLACE_SOON', 'REPLACE_NOW')
ORDER BY es.FAILURE_RISK_SCORE DESC;

SELECT 'ANALYTICS VIEWS CREATED' AS STATUS, CURRENT_TIMESTAMP() AS CREATED_AT;

