-- ============================================================================
-- TDF DATA PLATFORM - EXECUTIVE VIEWS
-- ============================================================================
-- C-Level Executive Dashboard Views
-- KPIs, Risk Scoring, Financial Impact, Market Context
-- Based on TDF 2024: EUR 799.1M Revenue, 42-53% EBITDAaL, BBB- Rating
-- ============================================================================

USE DATABASE TDF_DATA_PLATFORM;
USE SCHEMA ANALYTICS;

-- ============================================================================
-- EXECUTIVE KPI SUMMARY (Single-View Dashboard)
-- ============================================================================

CREATE OR REPLACE VIEW VW_EXECUTIVE_KPIS AS
SELECT 
    em.PERIOD_DATE,
    em.FISCAL_YEAR,
    em.FISCAL_MONTH,
    
    -- Revenue
    em.REVENUE_EUR,
    em.REVENUE_EUR / 1000000 AS REVENUE_EUR_M,
    
    -- EBITDA (Target: 42-53%)
    em.EBITDAAL_EUR,
    em.EBITDAAL_MARGIN_PCT,
    CASE 
        WHEN em.EBITDAAL_MARGIN_PCT >= 45 THEN 'GREEN'
        WHEN em.EBITDAAL_MARGIN_PCT >= 40 THEN 'AMBER'
        ELSE 'RED'
    END AS EBITDA_STATUS,
    
    -- YoY Growth
    em.YOY_GROWTH_PCT,
    
    -- Infrastructure
    (SELECT COUNT(*) FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES WHERE STATUS = 'ACTIVE') AS ACTIVE_SITES,
    (SELECT COUNT(*) FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.TOWERS) AS TOTAL_TOWERS,
    
    -- Colocation
    (SELECT AVG(COLOCATION_RATE) FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES WHERE STATUS = 'ACTIVE') AS AVG_COLOCATION_RATE,
    
    -- ESG
    bs.CARBON_EMISSIONS_TONNES,
    bs.RENEWABLE_ENERGY_PCT,
    bs.EQUALITY_INDEX_SCORE,
    bs.OVERALL_ESG_STATUS,
    
    -- Risk
    (SELECT AVG(FAILURE_RISK_SCORE) FROM TDF_DATA_PLATFORM.OPERATIONS.EQUIPMENT_STATUS) AS AVG_EQUIPMENT_RISK,
    (SELECT COUNT(*) FROM TDF_DATA_PLATFORM.DIGITAL_TWIN.DISCREPANCY_LOG WHERE STATUS = 'OPEN') AS OPEN_DISCREPANCIES,
    
    -- Credit Rating
    'BBB-' AS FITCH_RATING,
    'Stable' AS RATING_OUTLOOK

FROM TDF_DATA_PLATFORM.FINANCE.EBITDA_METRICS em
LEFT JOIN TDF_DATA_PLATFORM.ESG.BOARD_SCORECARD bs 
    ON em.FISCAL_YEAR = bs.FISCAL_YEAR 
    AND em.FISCAL_MONTH = MONTH(bs.REPORTING_DATE);

-- ============================================================================
-- REVENUE ANALYSIS (Segment & Client Breakdown)
-- ============================================================================

CREATE OR REPLACE VIEW VW_REVENUE_EXECUTIVE AS
SELECT 
    rs.PERIOD_DATE,
    rs.FISCAL_YEAR,
    rs.SEGMENT_LEVEL1,
    rs.SEGMENT_LEVEL2,
    SUM(rs.REVENUE_EUR) AS REVENUE_EUR,
    SUM(rs.REVENUE_EUR) / 1000000 AS REVENUE_EUR_M,
    SUM(rs.REVENUE_TARGET_EUR) AS TARGET_EUR,
    SUM(rs.VARIANCE_TO_TARGET_EUR) AS VARIANCE_EUR,
    AVG(rs.VARIANCE_TO_TARGET_PCT) AS VARIANCE_PCT,
    CASE 
        WHEN AVG(rs.VARIANCE_TO_TARGET_PCT) >= 0 THEN 'GREEN'
        WHEN AVG(rs.VARIANCE_TO_TARGET_PCT) >= -5 THEN 'AMBER'
        ELSE 'RED'
    END AS REVENUE_STATUS,
    
    -- Revenue Mix
    SUM(rs.REVENUE_EUR) / NULLIF(SUM(SUM(rs.REVENUE_EUR)) OVER (PARTITION BY rs.PERIOD_DATE), 0) * 100 AS REVENUE_MIX_PCT

FROM TDF_DATA_PLATFORM.FINANCE.REVENUE_BY_SEGMENT rs
GROUP BY rs.PERIOD_DATE, rs.FISCAL_YEAR, rs.SEGMENT_LEVEL1, rs.SEGMENT_LEVEL2;

-- Revenue by Client (Concentration Risk)
CREATE OR REPLACE VIEW VW_REVENUE_BY_CLIENT_EXECUTIVE AS
SELECT 
    rc.PERIOD_DATE,
    o.OPERATOR_NAME,
    rc.REVENUE_EUR,
    rc.REVENUE_EUR / 1000000 AS REVENUE_EUR_M,
    rc.REVENUE_SHARE_PCT,
    rc.ACTIVE_SITES,
    rc.NEW_SITES_IN_PERIOD,
    rc.CONCENTRATION_RISK,
    CASE 
        WHEN rc.REVENUE_SHARE_PCT > 30 THEN 'HIGH'
        WHEN rc.REVENUE_SHARE_PCT > 20 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS DEPENDENCY_LEVEL
FROM TDF_DATA_PLATFORM.FINANCE.REVENUE_BY_CLIENT rc
LEFT JOIN TDF_DATA_PLATFORM.CORE.OPERATORS o ON rc.OPERATOR_ID = o.OPERATOR_ID;

-- ============================================================================
-- EBITDA & MARGIN ANALYSIS
-- ============================================================================

CREATE OR REPLACE VIEW VW_EBITDA_BY_BU AS
SELECT 
    em.PERIOD_DATE,
    em.FISCAL_YEAR,
    em.BU_ID,
    bu.BU_NAME,
    em.REVENUE_EUR,
    em.OPEX_EUR,
    em.EBITDA_EUR,
    em.EBITDA_MARGIN_PCT,
    em.EBITDAAL_EUR,
    em.EBITDAAL_MARGIN_PCT,
    em.TRAFFIC_LIGHT AS STATUS,
    
    -- Margin Comparison
    LAG(em.EBITDAAL_MARGIN_PCT) OVER (PARTITION BY em.BU_ID ORDER BY em.PERIOD_DATE) AS PRIOR_MONTH_MARGIN,
    em.EBITDAAL_MARGIN_PCT - LAG(em.EBITDAAL_MARGIN_PCT) OVER (PARTITION BY em.BU_ID ORDER BY em.PERIOD_DATE) AS MARGIN_CHANGE

FROM TDF_DATA_PLATFORM.FINANCE.EBITDA_METRICS em
LEFT JOIN TDF_DATA_PLATFORM.CORE.BUSINESS_UNITS bu ON em.BU_ID = bu.BU_ID;

-- ============================================================================
-- RISK DASHBOARD (C-Level Risk View)
-- ============================================================================

CREATE OR REPLACE VIEW VW_RISK_DASHBOARD AS
SELECT 
    CURRENT_DATE() AS REPORT_DATE,
    
    -- Equipment Risk
    (SELECT COUNT(*) FROM TDF_DATA_PLATFORM.OPERATIONS.EQUIPMENT_STATUS WHERE FAILURE_RISK_SCORE >= 80) AS CRITICAL_EQUIPMENT_COUNT,
    (SELECT AVG(FAILURE_RISK_SCORE) FROM TDF_DATA_PLATFORM.OPERATIONS.EQUIPMENT_STATUS) AS AVG_EQUIPMENT_RISK_SCORE,
    CASE 
        WHEN (SELECT AVG(FAILURE_RISK_SCORE) FROM TDF_DATA_PLATFORM.OPERATIONS.EQUIPMENT_STATUS) <= 30 THEN 'GREEN'
        WHEN (SELECT AVG(FAILURE_RISK_SCORE) FROM TDF_DATA_PLATFORM.OPERATIONS.EQUIPMENT_STATUS) <= 50 THEN 'AMBER'
        ELSE 'RED'
    END AS EQUIPMENT_RISK_STATUS,
    
    -- Infrastructure Risk
    (SELECT AVG(RISK_SCORE) FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES WHERE STATUS = 'ACTIVE') AS AVG_SITE_RISK_SCORE,
    CASE 
        WHEN (SELECT AVG(RISK_SCORE) FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES WHERE STATUS = 'ACTIVE') <= 30 THEN 'GREEN'
        WHEN (SELECT AVG(RISK_SCORE) FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES WHERE STATUS = 'ACTIVE') <= 50 THEN 'AMBER'
        ELSE 'RED'
    END AS INFRASTRUCTURE_RISK_STATUS,
    
    -- Digital Twin Quality Risk
    (SELECT COUNT(*) FROM TDF_DATA_PLATFORM.DIGITAL_TWIN.DISCREPANCY_LOG WHERE STATUS = 'OPEN' AND SEVERITY = 'CRITICAL') AS CRITICAL_DISCREPANCIES,
    (SELECT AVG(OVERALL_SCORE) FROM TDF_DATA_PLATFORM.DIGITAL_TWIN.DATA_QUALITY_SCORES WHERE ENTITY_TYPE = 'COMPANY') AS DT_QUALITY_SCORE,
    CASE 
        WHEN (SELECT AVG(OVERALL_SCORE) FROM TDF_DATA_PLATFORM.DIGITAL_TWIN.DATA_QUALITY_SCORES WHERE ENTITY_TYPE = 'COMPANY') >= 80 THEN 'GREEN'
        WHEN (SELECT AVG(OVERALL_SCORE) FROM TDF_DATA_PLATFORM.DIGITAL_TWIN.DATA_QUALITY_SCORES WHERE ENTITY_TYPE = 'COMPANY') >= 60 THEN 'AMBER'
        ELSE 'RED'
    END AS DATA_QUALITY_STATUS,
    
    -- Compliance Risk
    (SELECT COUNT(*) FROM TDF_DATA_PLATFORM.ESG.COMPLIANCE_REQUIREMENTS WHERE COMPLIANCE_STATUS = 'NON_COMPLIANT') AS NON_COMPLIANT_COUNT,
    CASE 
        WHEN (SELECT COUNT(*) FROM TDF_DATA_PLATFORM.ESG.COMPLIANCE_REQUIREMENTS WHERE COMPLIANCE_STATUS = 'NON_COMPLIANT') = 0 THEN 'GREEN'
        WHEN (SELECT COUNT(*) FROM TDF_DATA_PLATFORM.ESG.COMPLIANCE_REQUIREMENTS WHERE COMPLIANCE_STATUS = 'NON_COMPLIANT') <= 2 THEN 'AMBER'
        ELSE 'RED'
    END AS COMPLIANCE_RISK_STATUS,
    
    -- Coverage Risk (Zones Blanches)
    (SELECT COUNT(*) FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES WHERE STATUS = 'PLANNED') AS PLANNED_SITES,
    
    -- Overall Risk
    'AMBER' AS OVERALL_RISK_STATUS;

-- ============================================================================
-- MARKET SHARE & COMPETITIVE POSITION
-- ============================================================================

CREATE OR REPLACE VIEW VW_MARKET_SHARE AS
SELECT 
    r.REGION_NAME,
    s.SITE_TYPE,
    COUNT(DISTINCT s.SITE_ID) AS TDF_SITES,
    
    -- Colocation represents market activity
    AVG(s.COLOCATION_RATE) AS AVG_COLOCATION,
    SUM(s.ANNUAL_REVENUE_EUR) AS TOTAL_REVENUE_EUR,
    
    -- Client Distribution
    COUNT(DISTINCT ci.OPERATOR_ID) AS OPERATORS_PRESENT,
    
    -- Capacity Utilization (proxy for market position)
    SUM(s.CURRENT_TENANTS) AS TOTAL_TENANTS,
    SUM(s.MAX_TENANTS) AS TOTAL_CAPACITY,
    ROUND(SUM(s.CURRENT_TENANTS) / NULLIF(SUM(s.MAX_TENANTS), 0) * 100, 1) AS CAPACITY_UTILIZATION_PCT

FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES s
LEFT JOIN TDF_DATA_PLATFORM.CORE.DEPARTMENTS d ON s.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.REGIONS r ON d.REGION_ID = r.REGION_ID
LEFT JOIN TDF_DATA_PLATFORM.INFRASTRUCTURE.CLIENT_INSTALLATIONS ci ON s.SITE_ID = ci.SITE_ID
WHERE s.STATUS = 'ACTIVE'
GROUP BY r.REGION_NAME, s.SITE_TYPE;

-- Client Concentration Analysis
CREATE OR REPLACE VIEW VW_CLIENT_CONCENTRATION AS
SELECT 
    o.OPERATOR_NAME,
    o.OPERATOR_TYPE,
    COUNT(DISTINCT ci.SITE_ID) AS SITES_USING,
    SUM(ci.ANNUAL_REVENUE_EUR) AS ANNUAL_REVENUE_EUR,
    SUM(ci.ANNUAL_REVENUE_EUR) / NULLIF((SELECT SUM(ANNUAL_REVENUE_EUR) FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.CLIENT_INSTALLATIONS), 0) * 100 AS REVENUE_PCT,
    CASE 
        WHEN SUM(ci.ANNUAL_REVENUE_EUR) / NULLIF((SELECT SUM(ANNUAL_REVENUE_EUR) FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.CLIENT_INSTALLATIONS), 0) > 0.30 THEN 'HIGH'
        WHEN SUM(ci.ANNUAL_REVENUE_EUR) / NULLIF((SELECT SUM(ANNUAL_REVENUE_EUR) FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.CLIENT_INSTALLATIONS), 0) > 0.20 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS CONCENTRATION_RISK,
    o.IS_STRATEGIC_CLIENT

FROM TDF_DATA_PLATFORM.CORE.OPERATORS o
LEFT JOIN TDF_DATA_PLATFORM.INFRASTRUCTURE.CLIENT_INSTALLATIONS ci ON o.OPERATOR_ID = ci.OPERATOR_ID
WHERE ci.STATUS = 'ACTIVE'
GROUP BY o.OPERATOR_NAME, o.OPERATOR_TYPE, o.IS_STRATEGIC_CLIENT
ORDER BY ANNUAL_REVENUE_EUR DESC;

-- ============================================================================
-- COST PER TOWER / SITE ANALYSIS
-- ============================================================================

CREATE OR REPLACE VIEW VW_COST_PER_TOWER AS
SELECT 
    t.TOWER_TYPE,
    r.REGION_NAME,
    COUNT(*) AS TOWER_COUNT,
    AVG(t.HEIGHT_M) AS AVG_HEIGHT_M,
    AVG(t.ORIGINAL_COST_EUR) AS AVG_ORIGINAL_COST,
    AVG(t.REPLACEMENT_COST_EUR) AS AVG_REPLACEMENT_COST,
    SUM(t.CURRENT_BOOK_VALUE_EUR) AS TOTAL_BOOK_VALUE,
    
    -- Maintenance Costs
    AVG(
        (SELECT SUM(mr.TOTAL_COST_EUR) 
         FROM TDF_DATA_PLATFORM.OPERATIONS.MAINTENANCE_RECORDS mr 
         WHERE mr.SITE_ID = t.SITE_ID 
         AND mr.PERFORMED_DATE >= DATEADD(YEAR, -1, CURRENT_DATE()))
    ) AS AVG_ANNUAL_MAINTENANCE_COST,
    
    -- Total Cost of Ownership
    AVG(t.REPLACEMENT_COST_EUR) + AVG(
        (SELECT COALESCE(SUM(mr.TOTAL_COST_EUR), 0) * 10  -- 10-year maintenance projection
         FROM TDF_DATA_PLATFORM.OPERATIONS.MAINTENANCE_RECORDS mr 
         WHERE mr.SITE_ID = t.SITE_ID)
    ) AS ESTIMATED_TCO_EUR

FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.TOWERS t
LEFT JOIN TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES s ON t.SITE_ID = s.SITE_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.DEPARTMENTS d ON s.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.REGIONS r ON d.REGION_ID = r.REGION_ID
GROUP BY t.TOWER_TYPE, r.REGION_NAME;

-- Revenue Per Site
CREATE OR REPLACE VIEW VW_REVENUE_PER_SITE AS
SELECT 
    s.SITE_TYPE,
    r.REGION_NAME,
    COUNT(*) AS SITE_COUNT,
    SUM(s.ANNUAL_REVENUE_EUR) AS TOTAL_REVENUE_EUR,
    AVG(s.ANNUAL_REVENUE_EUR) AS AVG_REVENUE_PER_SITE,
    SUM(s.ANNUAL_OPEX_EUR) AS TOTAL_OPEX_EUR,
    AVG(s.ANNUAL_OPEX_EUR) AS AVG_OPEX_PER_SITE,
    AVG(s.ANNUAL_REVENUE_EUR) - AVG(s.ANNUAL_OPEX_EUR) AS AVG_CONTRIBUTION_PER_SITE,
    ROUND((AVG(s.ANNUAL_REVENUE_EUR) - AVG(s.ANNUAL_OPEX_EUR)) / NULLIF(AVG(s.ANNUAL_REVENUE_EUR), 0) * 100, 1) AS CONTRIBUTION_MARGIN_PCT

FROM TDF_DATA_PLATFORM.INFRASTRUCTURE.SITES s
LEFT JOIN TDF_DATA_PLATFORM.CORE.DEPARTMENTS d ON s.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN TDF_DATA_PLATFORM.CORE.REGIONS r ON d.REGION_ID = r.REGION_ID
WHERE s.STATUS = 'ACTIVE'
GROUP BY s.SITE_TYPE, r.REGION_NAME;

-- ============================================================================
-- INVESTMENT SCENARIO SUMMARY
-- ============================================================================

CREATE OR REPLACE VIEW VW_INVESTMENT_SCENARIOS AS
SELECT 
    SCENARIO_NAME,
    SCENARIO_TYPE,
    TIME_HORIZON_YEARS,
    CAPEX_CHANGE_EUR / 1000000 AS CAPEX_CHANGE_EUR_M,
    OPEX_CHANGE_EUR / 1000000 AS OPEX_CHANGE_EUR_M,
    REVENUE_IMPACT_EUR / 1000000 AS REVENUE_IMPACT_EUR_M,
    NPV_EUR / 1000000 AS NPV_EUR_M,
    IRR_PCT,
    PAYBACK_YEARS,
    PROBABILITY_PCT,
    STATUS,
    CASE 
        WHEN IRR_PCT >= 15 AND PAYBACK_YEARS <= 5 THEN 'HIGHLY_ATTRACTIVE'
        WHEN IRR_PCT >= 10 AND PAYBACK_YEARS <= 7 THEN 'ATTRACTIVE'
        WHEN IRR_PCT >= 5 THEN 'MARGINAL'
        ELSE 'UNATTRACTIVE'
    END AS INVESTMENT_GRADE
FROM TDF_DATA_PLATFORM.COMMERCIAL.INVESTMENT_SCENARIOS
WHERE STATUS != 'REJECTED';

SELECT 'EXECUTIVE VIEWS CREATED' AS STATUS, CURRENT_TIMESTAMP() AS CREATED_AT;

